export const ACCOUNT_TYPES=Object.freeze({consumer:'consumer',business:'business',admin:'admin'});
export const PLACE_CATEGORIES=Object.freeze(['restaurant','cafe','gas_station','shopping','park','service','restroom','health','public_safety']);
export const BUSINESS_FEATURES=Object.freeze(['profile','locations','reviews','promotions','campaigns','contests','events','qr','analytics']);
export const QR_SCOPES=Object.freeze({checkin:'checkin',reward:'reward',contest:'contest'});
export const CATEGORY_LABELS=Object.freeze({restroom:'Bathrooms',restaurant:'Restaurants',cafe:'Cafes',gas_station:'Gas Stations',shopping:'Shopping',park:'Parks',service:'Services',health:'Health',public_safety:'Public Safety'});
export function normalizePlace(place){if(!place)return null;const intelligenceScore=place.intelligence_score==null?null:Number(place.intelligence_score);const freshnessLabel=place.intelligence_freshness_label??place.freshness_label??null;const conflict=Boolean(place.intelligence_has_recent_conflict??place.has_recent_conflict);const intelligenceFresh=place.intelligence_is_fresh??place.is_fresh??null;return{id:String(place.id),location_id:place.location_id?String(place.location_id):null,name:place.name??'Unnamed place',category:place.category??'service',rating:Number(place.rating??0),reviews:Number(place.review_count??place.reviews??0),distance:place.distance??null,distance_miles:place.distance_miles??null,distance_km:place.distance_km??null,latitude:place.latitude??null,longitude:place.longitude??null,description:place.description??'',address:place.address??[place.city,place.state,place.postal_code].filter(Boolean).join(', '),verified:Boolean(place.is_verified),cleanliness:place.cleanliness??null,cleanliness_pct:place.cleanliness_pct==null?null:Number(place.cleanliness_pct),accessible:Boolean(place.accessible),changing_table:Boolean(place.changing_table),smart_bathroom:Boolean(place.smart_bathroom),bathroom_verification_status:place.bathroom_verification_status??null,bathroom_verification_count:Number(place.bathroom_verification_count??0),bathroom_positive_count:Number(place.bathroom_positive_count??0),bathroom_negative_count:Number(place.bathroom_negative_count??0),source:place.source??null,source_dataset:place.source_dataset??null,freshness:place.updated_at??place.created_at??null,intelligence_score:intelligenceScore,freshness_label:freshnessLabel,intelligence_freshness_label:freshnessLabel,last_observed_at:place.last_observed_at??null,age_days:place.age_days==null?null:Number(place.age_days),community_agreement:place.community_agreement==null?null:Number(place.community_agreement),intelligence_weighted_community_agreement:place.intelligence_weighted_community_agreement==null?null:Number(place.intelligence_weighted_community_agreement),has_recent_conflict:conflict,intelligence_has_recent_conflict:conflict,intelligence_is_fresh:intelligenceFresh}}
export function categoryLabel(category){return CATEGORY_LABELS[category]||String(category||'service').replaceAll('_',' ')}
export function cleanlinessLabel(place){if(place?.cleanliness_pct!=null){if(place.cleanliness_pct>=85)return'Excellent';if(place.cleanliness_pct>=70)return'Good';if(place.cleanliness_pct>=50)return'Fair';return'Needs attention'}return place?.cleanliness||'Not rated'}
export function verificationLabel(place){if(place?.has_recent_conflict)return'⚠ Conflicting reports';if(place?.freshness_label&&place.freshness_label!=='No recent community observation')return place.freshness_label;if(place?.bathroom_verification_status==='verified'||place?.verified)return'Verified';if((place?.bathroom_verification_count??0)>0)return'Community checked';if(place?.bathroom_verification_status==='has_bathroom')return'Bathroom reported';return'Unverified'}
export function restroomSignal(place){if(place?.intelligence_score!=null)return Math.round(place.intelligence_score);const cleanliness=place?.cleanliness_pct==null?50:place.cleanliness_pct;const verification=Math.min(20,(place?.bathroom_verification_count??0)*2);const rating=(place?.rating??0)*4;return Math.round(Math.min(100,cleanliness*.7+verification+rating)}
export function intelligenceState(place){if(!place)return'unavailable';if(place.has_recent_conflict)return'conflicting';if(place.intelligence_is_fresh===false)return'stale';if(place.intelligence_score==null&&place.cleanliness_pct==null&&place.bathroom_verification_count===0)return'unavailable';return'available'}
export function intelligenceStateLabel(place){return({available:'Community intelligence available',stale:'Community intelligence may be out of date',conflicting:'Community reports conflict',unavailable:'Community intelligence unavailable'})[intelligenceState(place)]}
export function intelligenceConfidence(place){const state=intelligenceState(place);if(state==='unavailable')return'none';if(state==='conflicting')return'limited';if(place?.community_agreement!=null){const agreement=Number(place.community_agreement);if(agreement>=.8)return'high';if(agreement>=.6)return'moderate';return'limited'}return state==='stale'?'limited':'moderate'}
