import { requireSupabase } from '../lib/supabase';

export const ADMIN_RESOURCES = [
  ['profiles','Users'],['businesses','Businesses'],['business_members','Business members'],['locations','Locations'],['places','Places'],['reviews','Reviews'],['review_photos','Review photos'],['review_likes','Review likes'],['check_ins','Check-ins'],['reports','Reports'],['location_submissions','Location submissions'],['location_claims','Location claims'],['location_quality_reviews','Location quality'],['location_quality_observations','Quality observations'],['location_data_conflicts','Data conflicts'],
  ['location_hours','Location hours'],['amenities','Amenities'],['location_amenities','Location amenities'],['location_fixtures','Location fixtures'],['location_photos','Location photos'],['location_amenity_observations','Amenity observations'],['location_bathroom_verifications','Bathroom verifications'],['location_verification_points','Verification points'],['location_verification_campaigns','Verification campaigns'],['location_verification_targets','Verification targets'],['location_verification_observations','Verification observations'],
  ['promotions','Promotions'],['promotion_redemptions','Promotion redemptions'],['business_campaigns','Campaigns'],['business_events','Events'],['event_rsvps','Event RSVPs'],['contests','Contests'],['contest_entries','Contest entries'],['qr_codes','QR codes'],['qr_attribution_events','QR attribution'],['qr_redemptions','QR redemptions'],['business_earned_perks','Business earned perks'],['business_progression_events','Business progression'],['business_geofences','Business geofences'],['business_search_boosts','Business search boosts'],
  ['subscription_plans','Subscription plans'],['subscriptions','Subscriptions'],['pricing_catalog','Pricing'],['pricing_plans','Legacy pricing'],['pricing_family_catalog_v1','Pricing families'],['feature_catalog','Features'],['user_feature_entitlements','User entitlements'],['feature_access_events','Feature access events'],
  ['badges','Badges'],['user_badges','User badges'],['point_transactions','Point transactions'],['level_definitions','Levels'],['user_streaks','User streaks'],['progression_actions','Progression actions'],['progression_games','Games'],['progression_challenges','Challenges'],['progression_metric_events','Progression metrics'],['reward_transactions','Reward transactions'],['contributor_reputation','Contributor reputation'],['contributor_milestones','Contributor milestones'],
  ['favorites','Favorites'],['follows','Follows'],['social_posts','Social posts'],['social_post_likes','Post likes'],['social_post_comments','Post comments'],['social_post_saves','Post saves'],['social_post_reports','Post reports'],['social_activity','Social activity'],['social_challenge_entries','Social challenge entries'],['messages','Messages'],
  ['external_data_sources','Data sources'],['external_data_datasets','Datasets'],['external_location_records','External location records'],['external_observations','External observations'],['external_import_jobs','Import jobs'],['location_ingestion_jobs','Location jobs'],['location_sources','Location sources'],['location_confidence','Location confidence'],['location_address_backfills','Address backfills'],['data_feature_events','Data feature events'],
  ['notifications','Notifications'],['notification_preferences','Notification preferences'],['notification_push_subscriptions','Push subscriptions'],['notification_push_deliveries','Push deliveries'],['intelligence_notification_jobs','Intelligence notification jobs'],['intelligence_notification_deliveries','Intelligence notification deliveries'],['intelligence_action_links','Intelligence action links'],['live_network_events','Live network events'],
  ['user_feedback','User feedback'],['review_amenity_feedback','Review amenity feedback'],['support_requests','Support'],['ad_placements','Ad placements'],['analytics_events','Analytics events'],
  ['fleet_vehicles','Fleet vehicles'],['fleet_drivers','Fleet drivers'],['fleet_routes','Fleet routes'],['route_stops','Route stops'],['route_events','Route events'],['fleet_alerts','Fleet alerts'],['fleet_maintenance_records','Fleet maintenance'],['fleet_metric_snapshots','Fleet metrics'],['fleet_operational_events','Fleet events'],['fleet_driver_scorecards','Fleet scorecards'],['fleet_vehicle_daily_metrics','Fleet vehicle metrics'],
  ['enterprise_partner_networks','Enterprise networks'],['enterprise_partner_network_members','Enterprise network members'],['enterprise_partner_network_metrics','Enterprise network metrics'],['enterprise_partner_campaigns','Enterprise campaigns'],['enterprise_partner_campaign_outcomes','Enterprise outcomes'],['enterprise_partner_allocations','Enterprise allocations'],['business_engagement_attributions','Business attributions'],['partner_programs','Partner programs'],['partner_agreements','Partner agreements'],['partner_program_memberships','Partner memberships'],['partner_program_locations','Partner locations'],
  ['family_groups','Family groups'],['family_members','Family members'],['family_accounts','Family accounts'],['family_invites','Family invites'],['account_deletion_requests','Deletion requests'],['single_use_access_offers','Access offers'],['single_use_access_purchases','Access purchases'],
];
const ADMIN_KEYS={business_members:['business_id','user_id'],location_hours:['id'],location_amenities:['location_id','amenity_id'],favorites:['user_id','location_id'],follows:['follower_id','following_id'],user_badges:['user_id','badge_id'],level_definitions:['level'],location_confidence:['location_id'],notification_preferences:['user_id'],location_verification_targets:['campaign_id','location_id'],partner_program_memberships:['partner_program_id','business_id'],partner_program_locations:['partner_program_id','location_id'],enterprise_partner_network_members:['network_id','business_id'],family_members:['family_group_id','user_id']};
export const adminKeysFor=(table)=>ADMIN_KEYS[table]||['id'];
const allowed=new Set(ADMIN_RESOURCES.map(([table])=>table));
export function assertAdminResource(table){if(!allowed.has(table))throw new Error('Admin resource is not allowed.');return table;}
const keyRecord=(table,record)=>{const keys=adminKeysFor(table);if(record&&typeof record==='object')return record;if(keys.length!==1)throw new Error('Composite-key resource requires a key object.');return {[keys[0]]:record};};
const applyKeys=(query,table,record)=>{const key=keyRecord(table,record);return adminKeysFor(table).reduce((q,name)=>{if(key[name]==null)throw new Error(`Missing key: ${name}`);return q.eq(name,key[name]);},query);};
export async function listAdminRows(table,{limit=50,offset=0,order='created_at',ascending=false}={}){const client=requireSupabase();assertAdminResource(table);let query=client.from(table).select('*',{count:'exact'}).range(offset,offset+limit-1);try{const ordered=await query.order(order,{ascending});if(!ordered.error)return {data:ordered.data||[],count:ordered.count||0};}catch{}const {data,error,count}=await client.from(table).select('*',{count:'exact'}).range(offset,offset+limit-1);if(error)throw error;return {data:data||[],count:count||0};}
export async function createAdminRow(table,payload){const client=requireSupabase();assertAdminResource(table);const {data,error}=await client.from(table).insert(payload).select().single();if(error)throw error;return data;}
export async function updateAdminRow(table,record,payload){const client=requireSupabase();assertAdminResource(table);const {data,error}=await applyKeys(client.from(table).update(payload),table,record).select().single();if(error)throw error;return data;}
export async function deleteAdminRow(table,record){const client=requireSupabase();assertAdminResource(table);const {error}=await applyKeys(client.from(table).delete(),table,record);if(error)throw error;return {ok:true};}
