import { supabase } from '../lib/supabase';
import { hasBusinessFeature, normalizeBusinessPlan } from '../domain/entitlements';

async function user(){if(!supabase)throw new Error('Supabase is not configured.');const{data:{user:u},error}=await supabase.auth.getUser();if(error)throw error;if(!u)throw new Error('Sign in to continue.');return u}
async function rpc(name,args){await user();const{data,error}=await supabase.rpc(name,args);if(error)throw error;return data}
const rows=value=>{if(Array.isArray(value))return value;if(!value||typeof value!=='object')return[];for(const key of ['rows','items','locations','businesses','qrs','campaigns','contests','events','promotions','reviews','signals','data'])if(Array.isArray(value[key]))return value[key];return Object.values(value).filter(v=>v&&typeof v==='object'&&!Array.isArray(v)&&v.id)};
const one=value=>value&&typeof value==='object'&&!Array.isArray(value)?value:null;
async function requireFeature(businessId,feature){const businesses=await listBusinesses();const b=businesses.find(x=>String(x.id)===String(businessId));if(!b){const e=new Error('You do not have access to this business.');e.code='BUSINESS_ACCESS_DENIED';throw e}const plan=normalizeBusinessPlan(b?.plan||b?.business_plan||b?.subscription_plan);if(!hasBusinessFeature(plan,feature)){const e=new Error(`${plan.label} plan does not include ${feature}.`);e.code='FEATURE_NOT_ENTITLED';e.feature=feature;e.plan=plan.key;throw e}return plan}
async function requireBusinessLocation(businessId,locationId){if(!locationId)return null;const locations=await listLocations(businessId);const location=locations.find(x=>String(x.id)===String(locationId));if(!location){const e=new Error('This location is not managed by the selected business.');e.code='BUSINESS_LOCATION_ACCESS_DENIED';throw e}return location}
export async function listBusinesses(){const result=await rpc('get_business_dashboard',{});if(Array.isArray(result))return result;if(Array.isArray(result?.businesses))return result.businesses;if(result?.business)return[result.business];return rows(result)}
export const listLocations=async businessId=>rows(await rpc('business_list_locations',{p_business_id:businessId}));
export const createLocation=(businessId,payload)=>rpc('business_manage_location',{p_business_id:businessId,p_location_id:null,p_action:'create',p_payload:{name:payload.name,address:payload.address??null,city:payload.city??null,state:payload.state??null,postal_code:payload.postalCode??null,country:payload.country??'US',latitude:payload.latitude??null,longitude:payload.longitude??null,description:payload.description??null,phone:payload.phone??null,website:payload.website??null,is_active:true,is_premium:Boolean(payload.isPremium),accessible:Boolean(payload.accessible),changing_table:Boolean(payload.changingTable)}});
export const updateLocation=(businessId,locationId,payload)=>rpc('business_manage_location',{p_business_id:businessId,p_location_id:locationId,p_action:'update',p_payload:payload});
export const setLocationActive=(businessId,locationId,active)=>rpc('business_manage_location',{p_business_id:businessId,p_location_id:locationId,p_action:active?'update':'deactivate',p_payload:{is_active:active}});
export const listBusinessQrs=async businessId=>rows(await rpc('business_qr_detail',{p_business_id:businessId}));
export const createQr=async(businessId,locationId,payload)=>{await requireFeature(businessId,'qr');await requireBusinessLocation(businessId,locationId);return rpc('business_manage_qr',{p_business_id:businessId,p_location_id:locationId,p_qr_id:null,p_action:'create',p_payload:{label:payload.label,purpose:payload.purpose??'checkin',customization:payload.customization??{},active:true}})};
export const updateQr=async(businessId,qrId,payload)=>{await requireFeature(businessId,'qr');if(payload.locationId)await requireBusinessLocation(businessId,payload.locationId);return rpc('business_manage_qr',{p_business_id:businessId,p_location_id:payload.locationId??null,p_qr_id:qrId,p_action:'update',p_payload:{label:payload.label,purpose:payload.purpose,customization:payload.customization??{},active:payload.active}})};
export const setQrActive=async(businessId,qrId,active)=>{await requireFeature(businessId,'qr');return rpc('business_manage_qr',{p_business_id:businessId,p_location_id:null,p_qr_id:qrId,p_action:active?'activate':'deactivate',p_payload:{}})};
export const deleteQr=async(businessId,qrId)=>{await requireFeature(businessId,'qr');return rpc('business_manage_qr',{p_business_id:businessId,p_location_id:null,p_qr_id:qrId,p_action:'deactivate',p_payload:{}})};
export const listCampaigns=async businessId=>rows(await rpc('business_list_campaigns',{p_business_id:businessId}));
export const createCampaign=async(businessId,payload)=>{await requireFeature(businessId,'campaigns');return rpc('business_manage_campaign',{p_business_id:businessId,p_campaign_id:null,p_action:'create',p_name:payload.name,p_campaign_type:payload.type||'general',p_goal:payload.goal||'',p_status:payload.status||'draft'})};
export const updateCampaign=async(businessId,id,payload)=>{await requireFeature(businessId,'campaigns');return rpc('business_manage_campaign',{p_business_id:businessId,p_campaign_id:id,p_action:'update',p_name:payload.name,p_campaign_type:payload.type,p_goal:payload.goal,p_status:payload.status})};
export const deleteCampaign=async(businessId,id)=>{await requireFeature(businessId,'campaigns');return rpc('business_manage_campaign',{p_business_id:businessId,p_campaign_id:id,p_action:'pause'})};
export const listContests=async businessId=>rows(await rpc('business_list_contests',{p_business_id:businessId}));
export const createContest=async(businessId,payload)=>{await requireFeature(businessId,'contests');return rpc('business_create_contest',{p_business_id:businessId,p_name:payload.name,p_description:payload.description||'',p_starts_at:payload.startsAt,p_ends_at:payload.endsAt,p_scoring_rules:payload.scoringRules||{},p_rewards:payload.rewards||{}})};
export const updateContest=async(businessId,id,payload)=>{await requireFeature(businessId,'contests');return rpc('business_update_contest',{p_business_id:businessId,p_contest_id:id,p_name:payload.name,p_description:payload.description||'',p_starts_at:payload.startsAt,p_ends_at:payload.endsAt,p_scoring_rules:payload.scoringRules||{},p_rewards:payload.rewards||{},p_status:payload.status||'draft'})};
export const deleteContest=async(businessId,id)=>{await requireFeature(businessId,'contests');return rpc('business_delete_contest',{p_business_id:businessId,p_contest_id:id})};
export const listEvents=async businessId=>rows(await rpc('business_list_events',{p_business_id:businessId}));
export const createEvent=async(businessId,payload)=>{await requireFeature(businessId,'events');await requireBusinessLocation(businessId,payload.locationId);return rpc('business_manage_event',{p_business_id:businessId,p_event_id:null,p_action:'create',p_payload:{location_id:payload.locationId??null,title:payload.title,description:payload.description||'',event_date:payload.eventDate,event_time:payload.eventTime}})};
export const updateEvent=async(businessId,id,payload)=>{await requireFeature(businessId,'events');if(payload.locationId)await requireBusinessLocation(businessId,payload.locationId);return rpc('business_manage_event',{p_business_id:businessId,p_event_id:id,p_action:'update',p_payload:{location_id:payload.locationId??null,title:payload.title,description:payload.description||'',event_date:payload.eventDate,event_time:payload.eventTime}})};
export const deleteEvent=async(businessId,id)=>{await requireFeature(businessId,'events');return rpc('business_manage_event',{p_business_id:businessId,p_event_id:id,p_action:'delete',p_payload:{}})};
export const listPromotions=async businessId=>rows(await rpc('business_promotion_detail',{p_business_id:businessId}));
export const createPromotion=async(businessId,payload)=>{await requireFeature(businessId,'promotions');await requireBusinessLocation(businessId,payload.locationId);return rpc('business_manage_promotion',{p_business_id:businessId,p_promotion_id:null,p_action:'create',p_payload:{location_id:payload.locationId??null,title:payload.title,description:payload.description||'',discount:payload.discount||null,starts_at:payload.startsAt||null,ends_at:payload.endsAt||null,active:true}})};
export const updatePromotion=async(businessId,id,payload)=>{await requireFeature(businessId,'promotions');return rpc('business_manage_promotion',{p_business_id:businessId,p_promotion_id:id,p_action:'update',p_payload:{title:payload.title,description:payload.description||'',discount:payload.discount||null,active:payload.active??true,starts_at:payload.startsAt??null,ends_at:payload.endsAt??null}})};
export const setPromotionActive=async(businessId,id,active)=>{await requireFeature(businessId,'promotions');return rpc('business_manage_promotion',{p_business_id:businessId,p_promotion_id:id,p_action:active?'update':'deactivate',p_payload:{active}})};
export const deletePromotion=async(businessId,id)=>{await requireFeature(businessId,'promotions');return rpc('business_manage_promotion',{p_business_id:businessId,p_promotion_id:id,p_action:'deactivate',p_payload:{}})};
export const getAnalytics=async businessId=>one(await rpc('business_summary_analytics',{p_business_id:businessId}))||{};
export const getLocationIntelligence=async businessId=>rows(await rpc('business_location_intelligence',{p_business_id:businessId}));
export const getReviewAnalytics=async businessId=>one(await rpc('business_review_analytics',{p_business_id:businessId}))||{};
export const listBusinessReviews=async businessId=>rows(await rpc('business_review_detail',{p_business_id:businessId}));
export const replyToReview=(businessId,reviewId,reply)=>rpc('business_reply_review',{p_business_id:businessId,p_review_id:reviewId,p_reply:reply});
export async function getBusinessPerformance(businessId){const[analytics,intelligence,reviews]=await Promise.all([getAnalytics(businessId),getLocationIntelligence(businessId),getReviewAnalytics(businessId)]);const rowsData=Array.isArray(intelligence)?intelligence:[];const total=key=>rowsData.reduce((sum,row)=>sum+Number(row?.[key]||0),0);return{analytics:analytics||{},intelligence:rowsData,reviews:reviews||{},totals:{searches:total('searches'),views:total('views'),directions:total('directions'),arrivals:total('arrivals'),checkIns:total('check_ins'),reviews:total('reviews')},locationsWithConflicts:rowsData.filter(row=>row?.has_recent_conflict).length,freshLocations:rowsData.filter(row=>row?.is_fresh).length}}
export function performanceSummary(performance){if(!performance)return[];const t=performance.totals||{};return[{key:'demand',label:'Demand',value:t.searches||0,detail:`${t.views||0} location views`},{key:'conversion',label:'Intent',value:t.directions||0,detail:`${t.arrivals||0} arrivals`},{key:'community',label:'Community',value:t.checkIns||0,detail:`${t.reviews||0} reviews`},{key:'freshness',label:'Fresh locations',value:performance.freshLocations||0,detail:`${performance.locationsWithConflicts||0} with conflicting reports`}]}
