import { supabase } from '../lib/supabase';
async function user(){if(!supabase)throw new Error('Supabase is not configured.');const {data:{user:u},error}=await supabase.auth.getUser();if(error)throw error;if(!u)throw new Error('Sign in to continue.');return u}
async function rpc(name,args){await user();const{data,error}=await supabase.rpc(name,args);if(error)throw error;return data}
export const listBusinesses=()=>rpc('get_business_dashboard',{});
export const listLocations=businessId=>rpc('business_list_locations',{p_business_id:businessId});
export const createLocation=(businessId,payload)=>rpc('business_create_location',{p_business_id:businessId,p_name:payload.name,p_address:payload.address??null,p_city:payload.city??null,p_state:payload.state??null,p_postal_code:payload.postalCode??null,p_latitude:payload.latitude??null,p_longitude:payload.longitude??null,p_phone:payload.phone??null,p_website:payload.website??null});
export const updateLocation=(businessId,locationId,payload)=>rpc('business_manage_location',{p_business_id:businessId,p_location_id:locationId,p_action:'update',p_payload:{name:payload.name,address:payload.address,city:payload.city,state:payload.state,is_active:payload.isActive}});
export const setLocationActive=(businessId,locationId,active)=>rpc('business_set_location_active',{p_business_id:businessId,p_location_id:locationId,p_active:active});
export const listBusinessQrs=businessId=>rpc('business_qr_detail',{p_business_id:businessId});
export const createQr=(businessId,locationId,payload)=>rpc('business_create_custom_qr',{p_business_id:businessId,p_location_id:locationId,p_label:payload.label,p_purpose:payload.purpose??'checkin',p_action_type:payload.actionType??'checkin',p_action_payload:payload.actionPayload??{},p_customization:payload.customization??{},p_single_use:Boolean(payload.singleUse),p_max_redemptions:payload.maxRedemptions??null});
export const updateQr=(businessId,qrId,payload)=>rpc('business_manage_qr',{p_business_id:businessId,p_location_id:payload.locationId??null,p_qr_id:qrId,p_action:'update',p_payload:{label:payload.label,purpose:payload.purpose,action_type:payload.actionType,action_payload:payload.actionPayload??{},customization:payload.customization??{},active:payload.active,single_use:Boolean(payload.singleUse),max_redemptions:payload.maxRedemptions??null}});
export const setQrActive=(businessId,qrId,active)=>rpc('business_set_qr_active',{p_business_id:businessId,p_qr_id:qrId,p_active:active});
export const deleteQr=(businessId,qrId)=>rpc('business_delete_qr',{p_business_id:businessId,p_qr_id:qrId});
export const listCampaigns=businessId=>rpc('business_list_campaigns',{p_business_id:businessId});
export const createCampaign=(businessId,payload)=>rpc('business_create_campaign',{p_business_id:businessId,p_name:payload.name,p_campaign_type:payload.type||'general',p_goal:payload.goal||'',p_status:payload.status||'draft'});
export const updateCampaign=(businessId,id,payload)=>rpc('business_update_campaign',{p_business_id:businessId,p_campaign_id:id,p_name:payload.name,p_campaign_type:payload.type,p_goal:payload.goal,p_status:payload.status});
export const deleteCampaign=(businessId,id)=>rpc('business_delete_campaign',{p_business_id:businessId,p_campaign_id:id});
export const listContests=businessId=>rpc('business_list_contests',{p_business_id:businessId});
export const createContest=(businessId,payload)=>rpc('business_create_contest',{p_business_id:businessId,p_name:payload.name,p_description:payload.description||'',p_starts_at:payload.startsAt,p_ends_at:payload.endsAt,p_scoring_rules:payload.scoringRules||{},p_rewards:payload.rewards||{}});
export const updateContest=(businessId,id,payload)=>rpc('business_update_contest',{p_business_id:businessId,p_contest_id:id,p_name:payload.name,p_description:payload.description||'',p_starts_at:payload.startsAt,p_ends_at:payload.endsAt,p_scoring_rules:payload.scoringRules||{},p_rewards:payload.rewards||{},p_status:payload.status||'draft'});
export const deleteContest=(businessId,id)=>rpc('business_delete_contest',{p_business_id:businessId,p_contest_id:id});
export const listEvents=businessId=>rpc('business_list_events',{p_business_id:businessId});
export const createEvent=(businessId,payload)=>rpc('business_manage_event',{p_business_id:businessId,p_event_id:null,p_action:'create',p_payload:{location_id:payload.locationId??null,title:payload.title,description:payload.description||'',event_date:payload.eventDate,event_time:payload.eventTime}});
export const updateEvent=(businessId,id,payload)=>rpc('business_manage_event',{p_business_id:businessId,p_event_id:id,p_action:'update',p_payload:{location_id:payload.locationId??null,title:payload.title,description:payload.description||'',event_date:payload.eventDate,event_time:payload.eventTime}});
export const deleteEvent=(businessId,id)=>rpc('business_delete_event',{p_business_id:businessId,p_event_id:id});
export const listPromotions=businessId=>rpc('business_promotion_detail',{p_business_id:businessId});
export const createPromotion=(businessId,payload)=>rpc('business_manage_promotion',{p_business_id:businessId,p_promotion_id:null,p_action:'create',p_payload:{location_id:payload.locationId??null,title:payload.title,description:payload.description||'',discount:payload.discount||null,starts_at:payload.startsAt,ends_at:payload.endsAt}});
export const updatePromotion=(businessId,id,payload)=>rpc('business_manage_promotion',{p_business_id:businessId,p_promotion_id:id,p_action:'update',p_payload:{title:payload.title,description:payload.description||'',discount:payload.discount||null,active:payload.active??true,starts_at:payload.startsAt??null,ends_at:payload.endsAt??null}});
export const setPromotionActive=(businessId,id,active)=>rpc('business_set_promotion_active',{p_business_id:businessId,p_promotion_id:id,p_active:active});
export const deletePromotion=(businessId,id)=>rpc('business_delete_promotion',{p_business_id:businessId,p_id:id});
export const getAnalytics=businessId=>rpc('business_summary_analytics',{p_business_id:businessId});
export const getReviewAnalytics=businessId=>rpc('business_review_analytics',{p_business_id:businessId});
export const listBusinessReviews=businessId=>rpc('business_review_detail',{p_business_id:businessId});
export const replyToReview=(businessId,reviewId,reply)=>rpc('business_reply_review',{p_business_id:businessId,p_review_id:reviewId,p_reply:reply});
