import { supabase } from '../lib/supabase';
import { syncCheckInRewards } from './rewards';
import { recordBusinessEngagement, recordQrAttribution } from './businessLifecycle';
import { getCachedPacks,queueOfflineEvent } from './offlinePacks';

function notifyRuntime(name, detail={}){ if(typeof window==='undefined')return; window.dispatchEvent(new CustomEvent(name,{detail})); }
async function requireUser(){if(!supabase)throw new Error('Supabase is not configured.');const{data:{user},error}=await supabase.auth.getUser();if(error)throw error;if(!user)throw new Error('Sign in to continue.');return user;}
async function queueIfOffline(payload){if(typeof navigator!=='undefined'&&navigator.onLine)return null;const pack=(await getCachedPacks())[0];if(!pack)throw new Error('Save an offline map or business pack before going offline so check-ins can be queued.');return queueOfflineEvent({packId:pack.id,eventType:'consumer.check_in',payload});}
export async function createCheckIn({locationId,placeId=null,qrToken=null}={}){const user=await requireUser();const normalizedQr=String(qrToken||'').trim()||null;let targetPlaceId=placeId||locationId;if(!targetPlaceId&&normalizedQr){const{data:qr,error:qrError}=await supabase.from('qr_codes').select('location_id').eq('code',normalizedQr).eq('active',true).maybeSingle();if(qrError)throw qrError;if(!qr?.location_id)throw new Error('Invalid or inactive QR code');const{data:place,error:placeError}=await supabase.from('places').select('id').eq('location_id',qr.location_id).eq('is_active',true).limit(1).maybeSingle();if(placeError)throw placeError;if(!place?.id)throw new Error('This QR code is not linked to an active place.');targetPlaceId=place.id;}if(!targetPlaceId)throw new Error('A place is required to check in.');const queued=await queueIfOffline({locationId:targetPlaceId,qrToken:normalizedQr});if(queued){notifyRuntime('kleenest:offline-event-queued',{eventType:'consumer.check_in',eventId:queued.id});return {queued_offline:true,event:queued};}const{data,error}=await supabase.rpc('create_check_in',{p_place_id:targetPlaceId,p_qr_token:normalizedQr});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(row?.business_id)recordBusinessEngagement(row.business_id,{locationId:row.location_id,activityType:'check_in',source:normalizedQr?'qr_checkin':'check_in',metadata:{checkInId:row.check_in_id||row.id,qrCodeId:row.qr_code_id,userId:user.id}}).catch(()=>null);if(normalizedQr)recordQrAttribution(normalizedQr,'check_in','consumer',{checkInId:row?.check_in_id||row?.id,locationId:row?.location_id,qrCodeId:row?.qr_code_id}).catch(()=>null);if(row?.check_in_id||row?.id)syncCheckInRewards(row.check_in_id||row.id).catch(()=>null);notifyRuntime('kleenest:checkin-created',{checkInId:row?.check_in_id||row?.id,locationId:row?.location_id,qrCodeId:row?.qr_code_id,pointsAwarded:row?.points_awarded||0});notifyRuntime('kleenest:rewards-updated',{source:'checkin',checkInId:row?.check_in_id||row?.id});notifyRuntime('kleenest:business-analytics-updated',{source:normalizedQr?'qr_checkin':'check_in',businessId:row?.business_id,locationId:row?.location_id});return data;}
export async function listMyCheckIns(){const user=await requireUser();const{data,error}=await supabase.from('check_ins').select('id,location_id,qr_code_id,checked_in_at,verification_method,points_awarded,metadata').eq('user_id',user.id).order('checked_in_at',{ascending:false});if(error)throw error;return data??[];}
export async function getMyPoints(){const user=await requireUser();const{data,error}=await supabase.from('reward_transactions').select('points').eq('user_id',user.id);if(error)throw error;return(data??[]).reduce((sum,row)=>sum+Number(row.points||0),0);}
