import { supabase } from '../lib/supabase';
import { recordCheckInEvent } from './events';
import { syncCheckInRewards } from './rewards';
import { recordBusinessEngagement, recordQrAttribution } from './businessLifecycle';
import { getCachedPacks,queueOfflineEvent } from './offlinePacks';

function notifyRuntime(name, detail={}){ if(typeof window==='undefined')return; window.dispatchEvent(new CustomEvent(name,{detail})); }
async function requireUser(){if(!supabase)throw new Error('Supabase is not configured.');const{data:{user},error}=await supabase.auth.getUser();if(error)throw error;if(!user)throw new Error('Sign in to continue.');return user;}
async function queueIfOffline(payload){if(typeof navigator!=='undefined'&&navigator.onLine)return null;const pack=(await getCachedPacks())[0];if(!pack)throw new Error('Save an offline map or business pack before going offline so check-ins can be queued.');return queueOfflineEvent({packId:pack.id,eventType:'consumer.check_in',payload});}
export async function createCheckIn({locationId,placeId=null,qrToken=null}={}){const user=await requireUser();const targetPlaceId=placeId||locationId;if(!targetPlaceId)throw new Error('A place is required to check in.');const queued=await queueIfOffline({locationId:targetPlaceId,qrToken});if(queued){notifyRuntime('kleenest:offline-event-queued',{eventType:'consumer.check_in',eventId:queued.id});return {queued_offline:true,event:queued};}const{data,error}=await supabase.rpc('create_check_in',{p_place_id:targetPlaceId,p_qr_token:qrToken});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(row?.location_id)recordCheckInEvent({locationId:row.location_id,checkInId:row.id,qrCodeId:row.qr_code_id,pointsAwarded:row.points_awarded}).catch(()=>null);if(row?.business_id)recordBusinessEngagement(row.business_id,{locationId:row.location_id,activityType:'check_in',source:qrToken?'qr_checkin':'check_in',metadata:{checkInId:row.id,qrCodeId:row.qr_code_id,userId:user.id}}).catch(()=>null);if(qrToken)recordQrAttribution(qrToken,'check_in','consumer',{checkInId:row?.id,locationId:row?.location_id,qrCodeId:row?.qr_code_id}).catch(()=>null);if(row?.id)syncCheckInRewards(row.id).catch(()=>null);notifyRuntime('kleenest:checkin-created',{checkInId:row?.id,locationId:row?.location_id,qrCodeId:row?.qr_code_id,pointsAwarded:row?.points_awarded||0});notifyRuntime('kleenest:rewards-updated',{source:'checkin',checkInId:row?.id});notifyRuntime('kleenest:business-analytics-updated',{source:qrToken?'qr_checkin':'check_in',businessId:row?.business_id,locationId:row?.location_id});return data;}
export async function listMyCheckIns(){const user=await requireUser();const{data,error}=await supabase.from('check_ins').select('id,location_id,qr_code_id,checked_in_at,verification_method,points_awarded,metadata').eq('user_id',user.id).order('checked_in_at',{ascending:false});if(error)throw error;return data??[];}
export async function getMyPoints(){const user=await requireUser();const{data,error}=await supabase.from('reward_transactions').select('points').eq('user_id',user.id);if(error)throw error;return(data??[]).reduce((sum,row)=>sum+Number(row.points||0),0);}
