import { getLocationSignals } from './intelligence';
import { buildNotificationCandidates } from './intelligenceNotifications';

const asRows=value=>{if(Array.isArray(value))return value;if(!value||typeof value!=='object')return[];for(const key of ['rows','signals','locations','intelligence','items','data'])if(Array.isArray(value[key]))return value[key];return Object.values(value).filter(v=>v&&typeof v==='object'&&!Array.isArray(v));};
function scoreReason(signals={}){const reasons=[];if(Number(signals.demand_score)>=70)reasons.push('high demand');if(Number(signals.activity_score)>=60)reasons.push('recent activity');if(Number(signals.observation_count)>0)reasons.push(`${Number(signals.observation_count)} observations`);if(Number(signals.quality_score)>=80)reasons.push('strong community confidence');if(Number(signals.quality_score)>0&&Number(signals.quality_score)<60)reasons.push('quality signal needs attention');if(signals.operational_status==='attention')reasons.push('location needs attention');if(signals.operational_status==='stale')reasons.push('stale location signal');return reasons}
export function buildLocationRecommendation(snapshot,signals={}, {surface='consumer'}={}){if(!snapshot)return null;const reasons=scoreReason(signals);if(surface==='business'){if(signals.operational_status==='attention'||signals.operational_status==='stale')return{type:'operational_attention',priority:'high',title:'Location needs attention',body:'Recent network signals indicate that this location may need verification or operational follow-up.',reasons};if(Number(signals.demand_score)>=70)return{type:'demand_opportunity',priority:'high',title:'Demand opportunity',body:'Kleenest is seeing elevated interest around this location.',reasons};if(Number(signals.activity_score)>=60)return{type:'activity_opportunity',priority:'normal',title:'Community activity opportunity',body:'Recent check-ins, observations and reviews indicate an opportunity to activate the local community.',reasons};if(Number(signals.quality_score)>0&&Number(signals.quality_score)<60)return{type:'quality_attention',priority:'high',title:'Quality signal needs attention',body:'Community confidence is below the healthy range and deserves a closer look.',reasons};return null}if(surface==='fleet'){if(Number(signals.demand_score)>=70||Number(signals.activity_score)>=70)return{type:'high_activity_zone',priority:'high',title:'High-activity zone',body:'Recent demand and activity make this location a useful operational waypoint.',reasons};return{type:'normal_zone',priority:'normal',title:'Normal activity',body:'No elevated operational signal is currently detected.',reasons}}if(Number(signals.quality_score)>=80&&signals.operational_status!=='stale')return{type:'trusted_place',priority:'normal',title:'Trusted place',body:'Strong community confidence makes this a reliable place to consider.',reasons};if(Number(signals.demand_score)>=70)return{type:'popular_place',priority:'normal',title:'Popular nearby',body:'This place is receiving elevated interest from the Kleenest network.',reasons};return{type:'standard_place',priority:'low',title:'Nearby place',body:'This place has current Kleenest intelligence available.',reasons}}
export async function recommendLocation(placeId,{surface='consumer'}={}){const{snapshot,signals}=await getLocationSignals(placeId);return buildLocationRecommendation(snapshot,signals,{surface})}
export function buildBusinessRecommendations(value=[]){return asRows(value).map(row=>{const demand=Number(row.demand_signal||0);const observations=Number(row.observations||row.observation_count||0);const signals={demand_score:Math.min(100,Math.round(demand||Number(row.searches||0)*2+Number(row.directions||0)*2+Number(row.check_ins||0)*3)),activity_score:Math.min(100,Math.round(Number(row.check_ins||0)*3+Number(row.observations||0)*2+Number(row.reviews||0)*2)),observation_count:observations,quality_score:Number(row.intelligence_score||0),operational_status:row.has_recent_conflict?'attention':String(row.freshness_label||'').toLowerCase().includes('stale')?'stale':'normal'};const recommendation=buildLocationRecommendation(row,signals,{surface:'business'});return recommendation?{location_id:row.location_id,name:row.name,recommendation,signals}:null}).filter(Boolean)}
export function buildFleetRecommendations(value=[]){return asRows(value).map(row=>{const signals={demand_score:Number(row.demand_score||0),activity_score:Number(row.activity_score||0),quality_score:Number(row.quality_score||0),operational_status:row.operational_status||'normal'};return{location_id:row.location_id,name:row.name,recommendation:buildLocationRecommendation(row,signals,{surface:'fleet'}),signals}}).filter(row=>row.recommendation?.priority==='high').sort((a,b)=>(b.signals.demand_score+b.signals.activity_score)-(a.signals.demand_score+a.signals.activity_score))}
export function buildBusinessNotificationCandidates(value=[],options={}){return buildNotificationCandidates(asRows(value),{surface:'business',...options})}
export function buildFleetNotificationCandidates(value=[],options={}){return buildNotificationCandidates(asRows(value),{surface:'fleet',...options})}
export function buildConsumerNotificationCandidate(row,options={}){return buildNotificationCandidates([row],{surface:'consumer',...options})[0]||null}
export function rankLocationSignals(value=[]){return[...asRows(value)].sort((a,b)=>{const aScore=Number(a?.demand_score||0)+Number(a?.activity_score||0)+Number(a?.quality_score||0);const bScore=Number(b?.demand_score||0)+Number(b?.activity_score||0)+Number(b?.quality_score||0);return bScore-aScore})}
