import { supabase } from '../lib/supabase';
import { listLiveEvents, subscribeToLiveEvents } from './liveNetwork';
import { getBusinessPerformance } from './businessPerformance';
import { createPromotion, createCampaign, createEvent } from './business';

async function requireUser(){
  if(!supabase)throw new Error('Supabase is not configured.');
  const{data:{user},error}=await supabase.auth.getUser();
  if(error)throw error;
  if(!user)throw new Error('Sign in to continue.');
  return user;
}
export async function getLocationIntelligence(placeId){if(!supabase||!placeId)return null;const{data,error}=await supabase.from('location_intelligence_snapshot').select('*').eq('place_id',placeId).maybeSingle();if(error)throw error;return data}
export async function getRestroomIntelligence(placeId){if(!supabase||!placeId)return null;const{data,error}=await supabase.from('restroom_intelligence').select('*').eq('place_id',placeId).maybeSingle();if(error)throw error;return data}
export async function getLocationTrust(locationId){if(!supabase||!locationId)return null;const{data,error}=await supabase.rpc('kleenest_location_confidence',{p_location_id:locationId});if(error)throw error;return Array.isArray(data)?(data[0]||null):data}
export async function getBusinessLocationIntelligence(businessId,{start=null,end=null}={}){if(!supabase||!businessId)return[];await requireUser();const args={p_business_id:businessId};if(start)args.p_start=start;if(end)args.p_end=end;const{data,error}=await supabase.rpc('business_location_intelligence',args);if(error)throw error;return Array.isArray(data)?data:[]}
export function deriveLocationSignals(snapshot,liveEvents=[]){const row=snapshot||{};const events=Array.isArray(liveEvents)?liveEvents:[];const now=Date.now();const recent=events.filter(e=>{const t=Date.parse(e?.created_at||'');return Number.isFinite(t)&&now-t<=7200000});const count=types=>recent.filter(e=>types.includes(e.event_type)).length;const demand=Math.min(100,Math.round(Number(row.searches_7d||0)*2+Number(row.views_30d||0)*.5+Number(row.directions_30d||0)*2+Number(row.arrivals_30d||0)*3+recent.length*4));const activity=Math.min(100,Math.round(Number(row.arrivals_30d||0)*2+Number(row.checkins_30d||0)*3+Number(row.reviews_30d||0)*2+recent.length*5));const quality=Math.max(0,Math.min(100,Math.round(Number(row.intelligence_score||0))));const operationalStatus=count(['location.stale'])>0?'stale':count(['location.conflict'])>0?'attention':count(['location.verified'])>0?'verified':recent.some(e=>['user.arrived','user.qr_check_in'].includes(e.event_type))?'active':'normal';return{demand_score:demand,quality_score:quality,activity_score:activity,operational_status:operationalStatus,recent_event_count:recent.length,recent_arrivals:count(['user.arrived']),recent_checkins:count(['user.qr_check_in']),recent_verifications:count(['location.verified']),recent_conflicts:count(['location.conflict']),recent_stale_events:count(['location.stale']),calculated_at:new Date().toISOString()}}
export async function getLocationSignals(placeId,{liveEventLimit=100}={}){const snapshot=await getLocationIntelligence(placeId);if(!snapshot?.location_id)return{snapshot,signals:deriveLocationSignals(snapshot,[])};const liveEvents=await listLiveEvents({locationId:snapshot.location_id,limit:liveEventLimit});return{snapshot,signals:deriveLocationSignals(snapshot,liveEvents),liveEvents}}
export function subscribeToLocationSignals({locationId,onSignals,onEvent}={}){if(!locationId)return()=>{};let recentEvents=[];const handleEvent=event=>{recentEvents=[event,...recentEvents].slice(0,100);onEvent?.(event);onSignals?.(deriveLocationSignals(null,recentEvents),event)};return subscribeToLiveEvents({locationId,onEvent:handleEvent})}
export function intelligenceLabel(score){const value=Number(score||0);if(value>=85)return'Excellent confidence';if(value>=70)return'Good confidence';if(value>=50)return'Moderate confidence';return'Limited confidence'}
export function freshnessCopy(row){if(!row?.last_observed_at)return row?.freshness_label||'No recent community observation';return row.freshness_label||'Community observation available'}
export function intelligenceConfidence(row){return Math.max(0,Math.min(100,Math.round(Number(row?.intelligence_score||0))))}
export function trustSummary(trust){if(!trust)return{label:'Not yet verified',score:null,conflict:false};const score=trust.confidence_score==null?trust.confidence:trust.confidence_score;const conflict=Boolean(trust.has_recent_conflict||trust.conflict_count>0);return{label:conflict?'Conflicting community reports':Number(score||0)>=80?'Highly trusted':Number(score||0)>=60?'Community verified':Number(score||0)>=40?'Some evidence':'Limited evidence',score:score==null?null:Number(score),conflict}}
export const INTELLIGENCE_SIGNAL_TYPES=Object.freeze({DEMAND:'demand',QUALITY:'quality',ACTIVITY:'activity',OPERATIONS:'operations'});
const num=value=>Number(value||0);
export function deriveBusinessSignals(performance){const totals=performance?.totals||{},reviews=performance?.reviews||{},analytics=performance?.analytics||{},rows=Array.isArray(performance?.intelligence)?performance.intelligence:[];const searches=num(totals.searches),views=num(totals.views),directions=num(totals.directions),arrivals=num(totals.arrivals),checkIns=num(totals.checkIns),reviewCount=num(totals.reviews),averageRating=num(reviews.average_rating??reviews.avg_rating??analytics.average_rating),conflicts=num(performance?.locationsWithConflicts),stale=Math.max(rows.length-num(performance?.freshLocations),0),demandScore=searches+views*.5,activityScore=checkIns+reviewCount*2,operationalRisk=conflicts+stale;return[{type:'demand',key:'demand-opportunity',title:demandScore>0?'Demand opportunity detected':'Demand data is still building',score:Math.round(demandScore),evidence:`${searches} searches and ${views} location views`,priority:demandScore>=25?'high':demandScore>0?'medium':'low',action:demandScore>=25?'create-promotion':null},{type:'quality',key:'quality',title:averageRating?`Community rating: ${averageRating.toFixed(1)}`:'Quality signal is still building',score:averageRating?Math.round(averageRating*20):0,evidence:`${reviewCount} reviews`,priority:averageRating>0&&averageRating<3.5?'high':'medium',action:averageRating>0&&averageRating<3.5?'create-campaign':null},{type:'activity',key:'activity',title:activityScore>0?'Community activity is moving':'Community activity is quiet',score:Math.round(activityScore),evidence:`${checkIns} check-ins and ${reviewCount} reviews`,priority:activityScore>=10?'high':activityScore>0?'medium':'low',action:activityScore>0&&activityScore<10?'create-event':null},{type:'operations',key:'operations',title:operationalRisk?'Operational attention needed':'Operations look healthy',score:operationalRisk,evidence:`${conflicts} conflicting and ${stale} stale location signals`,priority:operationalRisk>=2?'high':operationalRisk?'medium':'low',action:null},{type:'demand',key:'conversion',title:directions>0?'High-intent traffic detected':'Intent data is still building',score:views?Math.round(directions/views*100):0,evidence:`${directions} direction requests from ${views} views`,priority:views&&directions/views>=.2?'high':'low',action:null},{type:'demand',key:'arrival-conversion',title:directions>0?'Arrival conversion is measurable':'Arrival data is still building',score:directions?Math.round(arrivals/directions*100):0,evidence:`${arrivals} arrivals from ${directions} direction requests`,priority:directions&&arrivals/directions>=.4?'high':'low',action:null}]}
export async function getBusinessIntelligence(businessId){const performance=await getBusinessPerformance(businessId);return{performance,signals:deriveBusinessSignals(performance)}}
export async function executeIntelligenceAction(businessId,signal,payload={}){if(!signal?.action)throw new Error('This intelligence signal has no available action.');switch(signal.action){case'create-promotion':return createPromotion(businessId,{locationId:payload.locationId??null,title:payload.title||'Demand opportunity promotion',description:payload.description||'Promotion created from a Kleenest demand signal.',discount:payload.discount||null,startsAt:payload.startsAt||null,endsAt:payload.endsAt||null});case'create-campaign':return createCampaign(businessId,{name:payload.name||'Quality improvement campaign',type:payload.type||'quality',goal:payload.goal||'Improve community experience and review sentiment.',status:payload.status||'draft'});case'create-event':return createEvent(businessId,{locationId:payload.locationId??null,title:payload.title||'Community activity event',description:payload.description||'Event created from a Kleenest activity signal.',eventDate:payload.eventDate,eventTime:payload.eventTime});default:throw new Error(`Unsupported intelligence action: ${signal.action}`)}}
export function rankSignals(signals){const weight={high:3,medium:2,low:1};return[...(signals||[])].sort((a,b)=>(weight[b.priority]||0)-(weight[a.priority]||0)||num(b.score)-num(a.score))}
