import { supabase } from '../lib/supabase';
import { listPlaces } from './places.js';
import { listExternalMapLocations } from './mapDiscovery.js';
import { createOfflinePack,getCachedLocations } from './offlinePacks.js';

const KEY='kleenest:location-bootstrap:v2';
const RADIUS_KM=10;
const CELL_DEGREES=.1;
const cellFor=({latitude,longitude})=>({cellLat:Number((Math.floor(Number(latitude)/CELL_DEGREES)*CELL_DEGREES).toFixed(2)),cellLng:Number((Math.floor(Number(longitude)/CELL_DEGREES)*CELL_DEGREES).toFixed(2))});
function boundsAround({latitude,longitude},radiusKm=RADIUS_KM){const lat=Number(latitude),lng=Number(longitude),dLat=radiusKm/111,dLng=radiusKm/(111*Math.max(.2,Math.cos(lat*Math.PI/180)));return{west:lng-dLng,south:lat-dLat,east:lng+dLng,north:lat+dLat};}
async function claimCell(location){if(!supabase)return true;const c=cellFor(location);const {data,error}=await supabase.rpc('claim_map_discovery_cell',{p_cell_lat:c.cellLat,p_cell_lng:c.cellLng,p_radius_m:RADIUS_KM*1000,p_lease_minutes:10});if(error)return true;return Boolean(data?.[0]?.should_refresh);}
async function persistSession(location,memberType='consumer',count=0,source='app_open'){if(!supabase)return;await supabase.from('location_discovery_sessions').insert({latitude:Number(location.latitude),longitude:Number(location.longitude),accuracy_m:Number(location.accuracy||0),radius_m:RADIUS_KM*1000,membership_type:memberType,discovered_count:count,metadata:{source,cell:cellFor(location)}}).then(()=>{}).catch(()=>{});}
export async function bootstrapLocationIntelligence({location,membershipType='consumer',signal,force=false}={}){if(!location||!Number.isFinite(Number(location.latitude))||!Number.isFinite(Number(location.longitude)))return{locations:[],source:'none',cached:false,refreshed:false};const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),9000);if(signal?.addEventListener)signal.addEventListener('abort',()=>controller.abort(),{once:true});try{const shouldRefresh=force||await claimCell(location);const primary=await listPlaces({category:'all',limit:500,userLocation:location,radiusKm:RADIUS_KM}).catch(()=>[]);let locations=Array.isArray(primary)?primary:[];if(!locations.length)locations=await listExternalMapLocations({userLocation:location,radiusKm:RADIUS_KM,limit:500}).catch(()=>[]);await persistSession(location,membershipType,locations.length,shouldRefresh?'app_open_refresh':'app_open_cached_cell');if(shouldRefresh&&locations.length)createOfflinePack({kind:'area',name:'Nearby Kleenest area',bounds:boundsAround(location)}).catch(()=>{});return{locations,source:primary.length?'canonical':'external',cached:!shouldRefresh,refreshed:shouldRefresh};}finally{clearTimeout(timeout);}}
export async function warmLocationIntelligence(location,{membershipType='consumer',force=false}={}){if(!location)return;const c=cellFor(location),cell=`${c.cellLat}:${c.cellLng}`,key=`${KEY}:${cell}`,stamp=Number(localStorage.getItem(key)||0);if(!force&&stamp&&Date.now()-stamp<5*60*1000)return;localStorage.setItem(key,String(Date.now()));try{await bootstrapLocationIntelligence({location,membershipType,force});}catch(_){} }
export async function loadBestAvailableLocationData(location){if(!location)return[];try{const live=await bootstrapLocationIntelligence({location});if(live.locations.length)return live.locations;}catch(_){}try{const rows=await getCachedLocations();return rows.map(r=>r?.snapshot||r).filter(Boolean);}catch(_){return[];}}
