import { supabase } from '../lib/supabase';

const DB_NAME='kleenest-offline-network';
const DB_VERSION=1;
const STORES=['packs','locations','businesses','events'];

function openDb(){return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined')return reject(new Error('Offline storage is unavailable in this browser.'));const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;STORES.forEach(name=>{if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'});});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('Unable to open offline storage.'));});}
async function putMany(storeName,rows){if(!rows?.length)return;const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(storeName,'readwrite');rows.forEach(row=>tx.objectStore(storeName).put(row));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
export async function cacheOfflinePack(pack,{locations=[],businesses=[]}={}){const normalized={...pack,id:String(pack.id),cached_at:new Date().toISOString()};await putMany('packs',[normalized]);await putMany('locations',locations.map(row=>({...row,pack_id:normalized.id,id:`${normalized.id}:location:${row.location_id||row.id}`})));await putMany('businesses',businesses.map(row=>({...row,pack_id:normalized.id,id:`${normalized.id}:business:${row.business_id||row.id}`})));return normalized;}
export async function queueOfflineEvent({packId,eventType,payload}){const row={id:crypto.randomUUID(),pack_id:packId,event_type:eventType,payload,created_at:new Date().toISOString(),synced_at:null};await putMany('events',[row]);return row;}
export async function syncOfflineEvents(){if(!supabase)return {synced:0,failed:0};const db=await openDb();const events=await new Promise((resolve,reject)=>{const tx=db.transaction('events','readonly');const req=tx.objectStore('events').getAll();req.onsuccess=()=>resolve(req.result.filter(row=>!row.synced_at));req.onerror=()=>reject(req.error);});let synced=0,failed=0;for(const event of events){const {error}=await supabase.from('offline_pack_events').insert({pack_id:event.pack_id,event_type:event.event_type,payload:event.payload,created_at:event.created_at});if(error)failed++;else{synced++;await new Promise((resolve,reject)=>{const tx=db.transaction('events','readwrite');tx.objectStore('events').put({...event,synced_at:new Date().toISOString()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}}db.close();return {synced,failed};}
export async function createOfflinePack({kind='area',name='Kleenest offline area',routeId=null,locationId=null,businessId=null,bounds=null}={}){if(!supabase)throw new Error('Supabase is not configured.');const {data,error}=await supabase.rpc('create_offline_pack',{p_kind:kind,p_name:name,p_route_id:routeId,p_location_id:locationId,p_business_id:businessId,p_bounds:bounds});if(error)throw error;return data;}
export async function getCachedPacks(){const db=await openDb();const rows=await new Promise((resolve,reject)=>{const tx=db.transaction('packs','readonly');const req=tx.objectStore('packs').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});db.close();return rows.sort((a,b)=>String(b.cached_at).localeCompare(String(a.cached_at)));}
if(typeof window!=='undefined')window.addEventListener('online',()=>{syncOfflineEvents().catch(()=>{})});
