import { normalizePlace } from '../domain/contracts';
import { supabase } from '../lib/supabase';
import { recordLocationView, recordSearch } from './events';

const demoPlaces=[
{id:'demo-restroom-1',name:'Kleenest Community Restroom',category:'restroom',rating:4.8,review_count:24,description:'A community-verified restroom with accessible facilities.',address:'100 Main Street',city:'Sparta',state:'IL',latitude:38.123,longitude:-89.701,cleanliness:'Excellent',cleanliness_pct:94,accessible:true,changing_table:true,bathroom_verification_status:'verified',bathroom_verification_count:18,bathroom_positive_count:17,bathroom_negative_count:1,is_verified:true,intelligence_score:91,freshness_label:'Observed this week'},
{id:'demo-restroom-2',name:'Riverside Public Restroom',category:'restroom',rating:4.4,review_count:12,description:'Public restroom near the riverfront and walking trail.',address:'1 Riverside Drive',city:'Sparta',state:'IL',latitude:38.117,longitude:-89.696,cleanliness:'Good',cleanliness_pct:78,accessible:true,changing_table:false,bathroom_verification_status:'verified',bathroom_verification_count:9,bathroom_positive_count:7,bathroom_negative_count:2,is_verified:true,intelligence_score:76,freshness_label:'Observed this month'},
{id:'demo-cafe',name:'Kleenest Coffee House',category:'cafe',rating:4.8,review_count:38,description:'A local coffee stop with a welcoming atmosphere.',address:'12 Main Street',latitude:38.627,longitude:-90.199},
{id:'demo-restaurant',name:'Main Street Market',category:'restaurant',rating:4.6,review_count:51,description:'A neighborhood restaurant serving the local community.',address:'24 Main Street',latitude:38.63,longitude:-90.205},
{id:'demo-gas',name:'River Road Fuel',category:'gas_station',rating:4.4,review_count:22,description:'Convenient fuel and everyday essentials.',address:'101 River Road',latitude:38.62,longitude:-90.19},
{id:'demo-shopping',name:'Downtown Goods',category:'shopping',rating:4.7,review_count:17,description:'Independent local shopping and specialty goods.',address:'7 Market Avenue',latitude:38.633,longitude:-90.2},
{id:'demo-park',name:'Riverside Park',category:'park',rating:4.9,review_count:29,description:'A clean outdoor space for walks, recreation, and events.',address:'1 Riverside Drive',latitude:38.615,longitude:-90.21}
];
export const CATEGORY_DEFINITIONS=[{slug:'restroom',name:'Bathrooms'},{slug:'restaurant',name:'Restaurants'},{slug:'cafe',name:'Cafes'},{slug:'gas_station',name:'Gas Stations'},{slug:'shopping',name:'Shopping'},{slug:'park',name:'Parks'},{slug:'service',name:'Services'},{slug:'health',name:'Health'},{slug:'public_safety',name:'Public Safety'}];
const PLACE_FIELDS='id,name,category,description,address,city,state,postal_code,latitude,longitude,rating,review_count,is_verified,location_id,created_at,updated_at';
const LOCATION_FIELDS='id,cleanliness,cleanliness_pct,accessible,changing_table,smart_bathroom,bathroom_verification_status,bathroom_verification_count,bathroom_positive_count,bathroom_negative_count,source,source_dataset,updated_at,created_at';
const INTELLIGENCE_FIELDS='location_id,place_id,intelligence_score,cleanliness_pct,verification_count,observation_count,reviews_30d,searches_7d,searches_30d,views_30d,directions_30d,arrivals_30d,checkins_30d,last_observed_at,calculated_at,freshness_label';
const DEFAULT_GPS_RADIUS_KM=30;
const DISCOVERY_RADIUS_KM=8;
const DISCOVERY_COOLDOWN_MS=5*60*1000;
let lastDiscoveryKey='';let lastDiscoveryAt=0;
function haversineKm(lat1,lon1,lat2,lon2){const R=6371,rad=Math.PI/180,dLat=(lat2-lat1)*rad,dLon=(lon2-lon1)*rad,a=Math.sin(dLat/2)**2+Math.cos(lat1*rad)*Math.cos(lat2*rad)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function addDistance(rows,userLocation){if(userLocation?.latitude==null||userLocation?.longitude==null)return rows;return rows.map(row=>row.latitude==null||row.longitude==null?row:{...row,distance_km:haversineKm(userLocation.latitude,userLocation.longitude,row.latitude,row.longitude),distance_miles:haversineKm(userLocation.latitude,userLocation.longitude,row.latitude,row.longitude)*.621371})}
function rankRestrooms(rows,{userLocation,sort='recommended'}={}){const enriched=addDistance(rows,userLocation);if(sort==='distance'&&userLocation)return[...enriched].sort((a,b)=>(a.distance_km??Infinity)-(b.distance_km??Infinity));if(sort==='cleanliness')return[...enriched].sort((a,b)=>(b.cleanliness_pct??-1)-(a.cleanliness_pct??-1));if(sort==='verified')return[...enriched].sort((a,b)=>(b.bathroom_verification_count??0)-(a.bathroom_verification_count??0));return[...enriched].sort((a,b)=>{const score=p=>(p.intelligence_score??((p.cleanliness_pct??50)*.55+Math.min(20,(p.bathroom_verification_count??0)*2)))-(p.distance_km??0)*2;return score(b)-score(a)})}
function browserLocation(){return new Promise(resolve=>{if(typeof window==='undefined'||!navigator.geolocation||!window.location.pathname.includes('/map'))return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy||0}),()=>resolve(null),{enableHighAccuracy:true,maximumAge:30000,timeout:10000})})}
function gpsBounds(userLocation,radiusKm=DEFAULT_GPS_RADIUS_KM){if(userLocation?.latitude==null||userLocation?.longitude==null)return null;const latDelta=radiusKm/111.32;const lonDelta=radiusKm/(111.32*Math.max(Math.cos(userLocation.latitude*Math.PI/180),0.2));return{south:userLocation.latitude-latDelta,west:userLocation.longitude-lonDelta,north:userLocation.latitude+latDelta,east:userLocation.longitude+lonDelta}}
async function discoverNearbyNetwork(userLocation){if(!supabase||userLocation?.latitude==null||userLocation?.longitude==null||typeof window==='undefined')return null;const key=`${userLocation.latitude.toFixed(2)}:${userLocation.longitude.toFixed(2)}`;const now=Date.now();if(key===lastDiscoveryKey&&now-lastDiscoveryAt<DISCOVERY_COOLDOWN_MS)return null;lastDiscoveryKey=key;lastDiscoveryAt=now;try{const{data,error}=await supabase.functions.invoke('ingest-map-candidates',{body:{latitude:userLocation.latitude,longitude:userLocation.longitude,radius_km:DISCOVERY_RADIUS_KM,source:'map_gps'}});if(error)return null;return data??null}catch{return null}}
async function enrichWithLocationData(rows){if(!supabase||!rows.length)return rows;const ids=[...new Set(rows.map(r=>r.location_id).filter(Boolean))];if(!ids.length)return rows;const{data,error}=await supabase.from('locations').select(LOCATION_FIELDS).in('id',ids);if(error)throw error;const byId=new Map((data??[]).map(location=>[String(location.id),location]));return rows.map(row=>({...row,...(byId.get(String(row.location_id))||{})}))}
async function enrichWithIntelligence(rows){if(!supabase||!rows.length)return rows;const ids=[...new Set(rows.map(r=>r.id).filter(Boolean))];if(!ids.length)return rows;const{data,error}=await supabase.from('location_intelligence_snapshot').select(INTELLIGENCE_FIELDS).in('place_id',ids);if(error)return rows;const byId=new Map((data??[]).map(i=>[String(i.place_id),i]));return rows.map(row=>{const intelligence=byId.get(String(row.id));return intelligence?{...row,...intelligence,intelligence_freshness_label:intelligence.freshness_label}:row})}
function amenityNamesFromFilters(amenities={}){return Object.entries(amenities).filter(([,enabled])=>Boolean(enabled)).map(([name])=>name)}
function normalizeNetworkRow(row){return normalizePlace({...row,location_id:row.location_id,source:row.source,source_dataset:row.source_dataset,source_external_id:row.source_external_id,distance_km:row.distance_meters==null?undefined:row.distance_meters/1000,distance_miles:row.distance_meters==null?undefined:row.distance_meters/1609.344,review_count:row.review_count??0,amenities:row.amenities??{},fixtures:row.fixtures??{},brand:row.brand??null,operator_name:row.operator_name??null,osm_tags:row.osm_tags??{}})}
async function listNetworkNearby({category='all',limit=100,search='',userLocation,amenities={},radiusKm=DEFAULT_GPS_RADIUS_KM}={}){if(!supabase||userLocation?.latitude==null||userLocation?.longitude==null)return null;const amenityNames=amenityNamesFromFilters(amenities);const{data,error}=await supabase.rpc('map_network_nearby_v1',{p_lat:userLocation.latitude,p_lng:userLocation.longitude,p_radius_m:Math.round(radiusKm*1000),p_limit:Math.max(limit,200),p_category:category==='all'?null:category,p_search:search.trim()||null,p_amenity_names:amenityNames.length?amenityNames:null});if(error)throw error;return(data??[]).map(normalizeNetworkRow)}
export async function listCategories(){if(!supabase)return CATEGORY_DEFINITIONS;const{data,error}=await supabase.from('place_categories').select('slug,name').order('name');if(error)return CATEGORY_DEFINITIONS;const existing=data??[],known=new Set(existing.map(x=>x.slug));return[...CATEGORY_DEFINITIONS.filter(x=>!known.has(x.slug)),...existing]}
export async function listPlaces({category='all',limit=100,bounds=null,search='',userLocation=null,sort='recommended',amenities={},radiusKm=DEFAULT_GPS_RADIUS_KM}={}){const resolvedLocation=userLocation||await browserLocation();if(!supabase){let rows=demoPlaces.filter(p=>(category==='all'||p.category===category)&&(!search||p.name.toLowerCase().includes(search.toLowerCase())));if(category==='restroom')rows=rows.filter(p=>(!amenities.accessible||p.accessible)&&(!amenities.changing_table||p.changing_table));return rankRestrooms(rows,{userLocation:resolvedLocation,sort}).slice(0,limit).map(normalizePlace)}
if(resolvedLocation&&!bounds)await discoverNearbyNetwork(resolvedLocation);
if(resolvedLocation&&!bounds){const networkRows=await listNetworkNearby({category,limit,search,userLocation:resolvedLocation,amenities,radiusKm});if(networkRows){let ranked=category==='restroom'?rankRestrooms(networkRows,{userLocation:resolvedLocation,sort}):[...networkRows].sort((a,b)=>{if(sort==='distance')return(a.distance_km??Infinity)-(b.distance_km??Infinity);if(sort==='cleanliness')return(b.cleanliness_pct??-1)-(a.cleanliness_pct??-1);if(sort==='verified')return(b.verification_confidence??0)-(a.verification_confidence??0);return(b.rating??0)-(a.rating??0)||(a.distance_km??Infinity)-(b.distance_km??Infinity)});if(search.trim()||category!=='all'||resolvedLocation)recordSearch({query:search,category,resultCount:ranked.length,locationIds:ranked.map(p=>p.location_id||p.id)});return ranked.slice(0,limit)}}
const spatialBounds=bounds||gpsBounds(resolvedLocation);let q=supabase.from('places').select(PLACE_FIELDS).eq('is_active',true);if(category!=='all')q=q.eq('category',category);if(search.trim())q=q.ilike('name',`%${search.trim()}%`);if(spatialBounds){const{south,west,north,east}=spatialBounds;q=q.gte('latitude',south).lte('latitude',north).gte('longitude',west).lte('longitude',east)}q=q.limit(Math.max(limit,200));const{data,error}=await q;if(error)throw error;let enriched=await enrichWithLocationData(data??[]);enriched=await enrichWithIntelligence(enriched);if(category==='restroom')enriched=enriched.filter(p=>(!amenities.accessible||p.accessible)&&(!amenities.changing_table||p.changing_table));let ranked=category==='restroom'?rankRestrooms(enriched,{userLocation:resolvedLocation,sort}):addDistance(enriched,resolvedLocation);if(resolvedLocation)ranked=ranked.filter(p=>p.distance_km==null||p.distance_km<=DEFAULT_GPS_RADIUS_KM);if(search.trim()||category!=='all'||resolvedLocation)recordSearch({query:search,category,resultCount:ranked.length,locationIds:ranked.map(p=>p.location_id||p.id)});return ranked.map(normalizePlace).slice(0,limit)}
export async function getPlace(id){if(!supabase)return normalizePlace(demoPlaces.find(p=>String(p.id)===String(id))??null);const{data,error}=await supabase.from('places').select(PLACE_FIELDS).eq('id',id).eq('is_active',true).maybeSingle();if(error)throw error;if(!data)return null;let[enriched]=await enrichWithLocationData([data]);[enriched]=await enrichWithIntelligence([enriched]);if(enriched.location_id)recordLocationView({locationId:enriched.location_id,placeId:enriched.id,category:enriched.category});return normalizePlace(enriched)}
export function filterRestrooms(places,{accessible=false,changingTable=false,minCleanliness=0}={}){return places.filter(p=>(!accessible||p.accessible)&&(!changingTable||p.changing_table)&&(p.cleanliness_pct==null||p.cleanliness_pct>=minCleanliness))}
