import { normalizePlace } from '../domain/contracts';
import { supabase } from '../lib/supabase';
import { recordLocationView, recordSearch } from './events';
import { getCachedLocations, getCachedBusinesses } from './offlinePacks';
import { getOfflinePlace } from './offlinePlace';

const offlineCacheRows=async({category='all',search='',userLocation,sort='recommended',limit=100}={})=>{try{const [locations,businesses]=await Promise.all([getCachedLocations(),getCachedBusinesses()]);const rows=[...locations.map(x=>({...x,...(x.snapshot||{}),category:x.snapshot?.category||x.category||'restroom',latitude:x.snapshot?.latitude??x.latitude,longitude:x.snapshot?.longitude??x.longitude,location_id:x.location_id||x.snapshot?.location_id||x.id})),...businesses.map(x=>({...x,...(x.snapshot||{}),category:x.snapshot?.category||x.category||'business',latitude:x.snapshot?.latitude??x.latitude,longitude:x.snapshot?.longitude??x.longitude,location_id:x.snapshot?.location_id||x.id}))];let filtered=rows.filter(r=>(category==='all'||r.category===category)&&(!search||String(r.name||'').toLowerCase().includes(search.toLowerCase())));if(userLocation?.latitude!=null&&userLocation?.longitude!=null){const R=6371,rad=Math.PI/180;filtered=filtered.map(r=>{if(r.latitude==null||r.longitude==null)return r;const dLat=(r.latitude-userLocation.latitude)*rad,dLon=(r.longitude-userLocation.longitude)*rad,a=Math.sin(dLat/2)**2+Math.cos(userLocation.latitude*rad)*Math.cos(r.latitude*rad)*Math.sin(dLon/2)**2;const km=R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));return {...r,distance_km:km,distance_miles:km*.621371}}).filter(r=>r.distance_km==null||r.distance_km<=50);if(sort==='distance')filtered.sort((a,b)=>(a.distance_km??Infinity)-(b.distance_km??Infinity));else if(sort==='cleanliness')filtered.sort((a,b)=>(b.cleanliness_pct??-1)-(a.cleanliness_pct??-1));else if(sort==='verified')filtered.sort((a,b)=>(b.bathroom_verification_count??b.verification_count??0)-(a.bathroom_verification_count??a.verification_count??0));}return filtered.slice(0,limit).map(r=>normalizePlace({...r,source:r.source||'offline_cache',source_dataset:r.source_dataset||'kleenest_offline_pack'}));}catch{return[]}};
const demoPlaces=[{id:'demo-restroom-1',name:'Kleenest Community Restroom',category:'restroom',rating:4.8,review_count:24,description:'A community-verified restroom with accessible facilities.',address:'100 Main Street',city:'Sparta',state:'IL',latitude:38.123,longitude:-89.701,cleanliness:'Excellent',cleanliness_pct:94,accessible:true,changing_table:true,bathroom_verification_status:'verified',bathroom_verification_count:18,bathroom_positive_count:17,bathroom_negative_count:1,is_verified:true,intelligence_score:91,freshness_label:'Observed this week'},{id:'demo-restroom-2',name:'Riverside Public Restroom',category:'restroom',rating:4.4,review_count:12,description:'Public restroom near the riverfront and walking trail.',address:'1 Riverside Drive',city:'Sparta',state:'IL',latitude:38.117,longitude:-89.696,cleanliness:'Good',cleanliness_pct:78,accessible:true,changing_table:false,bathroom_verification_status:'verified',bathroom_verification_count:9,bathroom_positive_count:7,bathroom_negative_count:2,is_verified:true,intelligence_score:76,freshness_label:'Observed this month'}];
export const CATEGORY_DEFINITIONS=[{slug:'restroom',name:'Bathrooms'},{slug:'restaurant',name:'Restaurants'},{slug:'cafe',name:'Cafes'},{slug:'gas_station',name:'Gas Stations'},{slug:'shopping',name:'Shopping'},{slug:'park',name:'Parks'},{slug:'service',name:'Services'},{slug:'health',name:'Health'},{slug:'public_safety',name:'Public Safety'}];
const PLACE_FIELDS='id,name,category,description,address,city,state,postal_code,latitude,longitude,rating,review_count,is_verified,location_id,created_at,updated_at';
const DEFAULT_GPS_RADIUS_KM=50;
const DISCOVERY_COOLDOWN_MS=5*60*1000;
let lastDiscoveryKey='';let lastDiscoveryAt=0;
function haversineKm(a,b,c,d){const R=6371,r=Math.PI/180,x=(c-a)*r,y=(d-b)*r,z=Math.sin(x/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function addDistance(rows,u){if(!u)return rows;return rows.map(r=>r.latitude==null||r.longitude==null?r:{...r,distance_km:haversineKm(u.latitude,u.longitude,r.latitude,r.longitude),distance_miles:haversineKm(u.latitude,u.longitude,r.latitude,r.longitude)*.621371})}
function rankRestrooms(rows,{userLocation,sort='recommended'}={}){const e=addDistance(rows,userLocation);if(sort==='distance'&&userLocation)return[...e].sort((a,b)=>(a.distance_km??Infinity)-(b.distance_km??Infinity));if(sort==='cleanliness')return[...e].sort((a,b)=>(b.cleanliness_pct??-1)-(a.cleanliness_pct??-1));if(sort==='verified')return[...e].sort((a,b)=>(b.bathroom_verification_count??0)-(a.bathroom_verification_count??0));return e}
function browserLocation(){return new Promise(resolve=>{if(typeof navigator==='undefined'||!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy||0}),()=>resolve(null),{enableHighAccuracy:true,maximumAge:30000,timeout:10000})})}
function gpsBounds(u,r=50){if(!u)return null;const d=r/111.32,l=r/(111.32*Math.max(Math.cos(u.latitude*Math.PI/180),.2));return{south:u.latitude-d,west:u.longitude-l,north:u.latitude+d,east:u.longitude+l}}
async function discoverNearbyNetwork(u){if(!supabase||!u||typeof window==='undefined')return null;const key=`${u.latitude.toFixed(2)}:${u.longitude.toFixed(2)}`,now=Date.now();if(key===lastDiscoveryKey&&now-lastDiscoveryAt<DISCOVERY_COOLDOWN_MS)return null;lastDiscoveryKey=key;lastDiscoveryAt=now;try{const{data,error}=await supabase.functions.invoke('ingest-map-candidates',{body:{latitude:u.latitude,longitude:u.longitude,radius_km:12,source:'map_gps'}});return error?null:data??null}catch{return null}}
async function listNetworkNearby({category='all',limit=100,search='',userLocation,amenities={},radiusKm=50}={}){if(!supabase||!userLocation)return null;const names=Object.entries(amenities).filter(([,v])=>v).map(([k])=>k);const{data,error}=await supabase.rpc('map_network_nearby_v1',{p_lat:userLocation.latitude,p_lng:userLocation.longitude,p_radius_m:Math.round(radiusKm*1000),p_limit:Math.max(limit,500),p_category:category==='all'?null:category,p_search:search.trim()||null,p_amenity_names:names.length?names:null});if(error)throw error;return data??[]}
function demoFallback({category,search,userLocation,sort,limit}){let r=demoPlaces.filter(p=>(category==='all'||p.category===category)&&(!search||p.name.toLowerCase().includes(search.toLowerCase())));r=addDistance(r,userLocation);return category==='restroom'?rankRestrooms(r,{userLocation,sort}).slice(0,limit).map(normalizePlace):r.slice(0,limit).map(normalizePlace)}
export async function listCategories(){if(!supabase)return CATEGORY_DEFINITIONS;const{data,error}=await supabase.from('place_categories').select('slug,name').order('name');return error?CATEGORY_DEFINITIONS:data?.length?data:CATEGORY_DEFINITIONS}
export async function listPlaces({category='all',limit=100,bounds=null,search='',userLocation=null,sort='recommended',amenities={},radiusKm=50}={}){const u=userLocation||await browserLocation();const online=typeof navigator==='undefined'||navigator.onLine;if(!online){const cached=await offlineCacheRows({category,search,userLocation:u,sort,limit});return cached.length?cached:demoFallback({category,search,userLocation:u,sort,limit})}if(!supabase)return demoFallback({category,search,userLocation:u,sort,limit});if(u&&!bounds)await discoverNearbyNetwork(u);if(u&&!bounds){const n=await listNetworkNearby({category,limit,search,userLocation:u,amenities,radiusKm});if(n?.length){const ranked=category==='restroom'?rankRestrooms(n,{userLocation:u,sort}):addDistance(n,u);return ranked.slice(0,limit).map(normalizePlace)}}const b=bounds||gpsBounds(u);let q=supabase.from('places').select(PLACE_FIELDS).eq('is_active',true);if(category!=='all')q=q.eq('category',category);if(search.trim())q=q.ilike('name',`%${search.trim()}%`);if(b)q=q.gte('latitude',b.south).lte('latitude',b.north).gte('longitude',b.west).lte('longitude',b.east);const{data,error}=await q.limit(Math.max(limit,500));if(error)throw error;let rows=data??[];if(!rows.length){const cached=await offlineCacheRows({category,search,userLocation:u,sort,limit});if(cached.length)return cached}rows=addDistance(rows,u);if(category==='restroom')rows=rankRestrooms(rows,{userLocation:u,sort});return rows.slice(0,limit).map(normalizePlace)}
export async function getPlace(id){if(typeof navigator!=='undefined'&&!navigator.onLine){const cached=await getOfflinePlace(id);if(cached)return normalizePlace(cached);return normalizePlace(demoPlaces.find(p=>String(p.id)===String(id))??null)}if(!supabase)return normalizePlace(demoPlaces.find(p=>String(p.id)===String(id))??null);const{data,error}=await supabase.from('places').select(PLACE_FIELDS).eq('id',id).eq('is_active',true).maybeSingle();if(error)throw error;return normalizePlace(data||demoPlaces.find(p=>String(p.id)===String(id))||null)}
export function filterRestrooms(places,{accessible=false,changingTable=false,minCleanliness=0}={}){return places.filter(p=>(!accessible||p.accessible)&&(!changingTable||p.changing_table)&&(p.cleanliness_pct==null||p.cleanliness_pct>=minCleanliness))}