import { supabase } from '../lib/supabase';
import { VAPID_PUBLIC_KEY } from '../config/push';
const STORAGE_KEY='kleenest_push_subscription';
function supported(){return typeof window!=='undefined'&&'Notification' in window&&'serviceWorker' in navigator&&'PushManager' in window;}
function urlBase64ToUint8Array(value){const padding='='.repeat((4-(value.length%4))%4);const base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));}
export function pushNotificationsSupported(){return supported();}
export async function getPushPermission(){if(!supported())return'unsupported';return Notification.permission;}
export async function requestPushPermission(){if(!supported())return'unsupported';return Notification.requestPermission();}
export async function registerPushSubscription({serviceWorkerUrl='/sw.js'}={}){if(!supported())return null;const permission=await requestPushPermission();if(permission!=='granted')return null;const registration=await navigator.serviceWorker.register(serviceWorkerUrl);let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)});const json=subscription.toJSON();if(typeof localStorage!=='undefined')localStorage.setItem(STORAGE_KEY,JSON.stringify(json));if(!supabase)return subscription;const {data:{user}}=await supabase.auth.getUser();if(!user)return subscription;const {error}=await supabase.rpc('register_notification_push_subscription',{p_endpoint:json.endpoint,p_subscription:json});if(error)throw error;return subscription;}
export async function unregisterPushSubscription(){if(!supported())return false;const registration=await navigator.serviceWorker.getRegistration('/');const subscription=await registration?.pushManager.getSubscription();if(!subscription)return false;const endpoint=subscription.endpoint;await subscription.unsubscribe();if(typeof localStorage!=='undefined')localStorage.removeItem(STORAGE_KEY);if(supabase){const {data:{user}}=await supabase.auth.getUser();if(user){const {error}=await supabase.rpc('remove_notification_push_subscription',{p_endpoint:endpoint});if(error)throw error;}}return true;}
