import {useEffect,useState} from 'react';
import {ArrowLeft,Check,Lock,RefreshCw,Sparkles} from 'lucide-react';
import {Link} from 'react-router-dom';
import {listBusinesses} from '../services/business';
import {normalizeBusinessPlan,BUSINESS_PLANS} from '../domain/entitlements';

const FEATURE_LABELS={profile:'Business profile',locations:'Locations',reviews:'Reviews',basic_analytics:'Basic analytics',qr:'QR check-ins',campaigns:'Campaigns',promotions:'Promotions',events:'Events',contests:'Contests',advanced_analytics:'Advanced analytics',engagement_attribution:'Engagement attribution',multi_location:'Multi-location management',priority_support:'Priority support'};

export default function BusinessEntitlementsPage(){const[business,setBusiness]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');async function load(){setLoading(true);setError('');try{const rows=await listBusinesses();setBusiness(rows?.[0]||null)}catch(e){setError(e.message||'Unable to load business plan.')}finally{setLoading(false)}}useEffect(()=>{load()},[]);if(loading)return <section className="page"><div className="empty-state">Loading business plan…</div></section>;if(error)return <section className="page"><div className="empty-state"><h2>Plan unavailable</h2><p>{error}</p><button className="secondary" onClick={load}><RefreshCw size={16}/>Retry</button></div></section>;if(!business)return <section className="page"><div className="empty-state"><h2>No business account</h2><p>Connect a business to manage plan features.</p><Link className="secondary" to="/business/dashboard">Business dashboard</Link></div></section>;const plan=normalizeBusinessPlan(business.plan||business.business_plan||business.subscription_plan);const plans=Object.values(BUSINESS_PLANS);return <section className="page"><Link className="back-link" to="/business/dashboard"><ArrowLeft size={16}/>Business dashboard</Link><div className="page-header"><div><span className="eyebrow">BUSINESS PLAN</span><h1>{plan.label}</h1><p>See exactly which Kleenest capabilities are available to this business.</p></div><Sparkles size={30}/></div><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">CURRENT PLAN</span><h2>{business.name||'Your business'} · {plan.label}</h2></div></div><div className="business-insights"><div><strong>{plan.features.length}</strong><span>enabled features</span></div><div><strong>{plan.key==='enterprise'?'∞':plan.key==='growth'?'Growth':'Core'}</strong><span>service tier</span></div></div></section><div className="business-grid">{plans.map(p=><section className={`detail-panel ${p.key===plan.key?'selected':''}`} key={p.key}><span className="eyebrow">{p.label.toUpperCase()}</span><h2>{p.key===plan.key?'Current plan':p.label}</h2><div className="management-list">{p.features.map(feature=><div className="management-item" key={feature}><span><strong>{FEATURE_LABELS[feature]||feature.replaceAll('_',' ')}</strong><small>{p.key===plan.key?'Included':'Available on '+p.label}</small></span>{p.key===plan.key?<Check size={18}/>:<Lock size={18}/>}</div>)}</div>{p.key!==plan.key&&<button className="secondary" disabled>Upgrade path ready</button>}</section>)}</div></section>}
