import {useEffect,useState} from 'react';
import {BarChart3,Building2,QrCode,RefreshCw,ShieldCheck,Star,ToggleLeft,ToggleRight} from 'lucide-react';
import {Link,useSearchParams} from 'react-router-dom';
import {listBusinesses,listLocations,listBusinessQrs,getAnalytics,getLocationIntelligence,getReviewAnalytics,setQrActive,listCampaigns,listContests,listEvents,listPromotions} from '../services/business';
import {getBusinessLifecycleAnalytics} from '../services/businessLifecycle';
import {useAuth} from '../context/AuthContext';
import BusinessManagePage from './BusinessManagePage';
import {intelligenceLabel,trustSummary,getBusinessIntelligence,executeIntelligenceAction} from '../services/intelligence';
import FeatureNavLinks from '../components/FeatureNavLinks';
function Card({children}){return <section className="detail-panel business-card">{children}</section>}
const n=v=>v==null?'—':Number.isFinite(Number(v))?Number(v):v;
const firstNumber=(v,keys=[])=>{if(typeof v==='number')return v;if(Array.isArray(v))return v.reduce((s,r)=>s+Number(r?.value??r?.count??0),0);for(const k of keys)if(v?.[k]!=null)return Number(v[k])||0;return 0};
const actionLabel=a=>a==='create-promotion'?'Create promotion':a==='create-campaign'?'Create campaign':a==='create-event'?'Create event':a;
export default function BusinessDashboardPage(){
 const{authenticated,loading:authLoading}=useAuth();const[params]=useSearchParams();
 const[data,setData]=useState({businesses:[],locations:[],qrs:[],analytics:null,intelligence:[],reviews:null,campaigns:[],contests:[],events:[],promotions:[],lifecycle:null,signals:[]});
 const[active,setActive]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null),[qrBusy,setQrBusy]=useState(null),[actionBusy,setActionBusy]=useState(null),[message,setMessage]=useState('');
 async function load(id=null){setLoading(true);setError(null);setMessage('');try{const businesses=await listBusinesses();const business=businesses?.find(b=>b.id===id)||businesses?.[0];if(!business){setData(d=>({...d,businesses:[]}));setActive(null);return}setActive(business.id);const[locations,qrs,analytics,intelligence,reviews,campaigns,contests,events,promotions]=await Promise.all([listLocations(business.id),listBusinessQrs(business.id),getAnalytics(business.id),getLocationIntelligence(business.id),getReviewAnalytics(business.id),listCampaigns(business.id),listContests(business.id),listEvents(business.id),listPromotions(business.id)]);let lifecycle=null,signals=[];try{lifecycle=await getBusinessLifecycleAnalytics(business.id)}catch(e){console.warn(e)}try{signals=(await getBusinessIntelligence(business.id)).signals||[]}catch(e){console.warn(e)}setData({businesses,locations:locations||[],qrs:qrs||[],analytics:analytics||null,intelligence:intelligence||[],reviews:reviews||null,campaigns:campaigns||[],contests:contests||[],events:events||[],promotions:promotions||[],lifecycle,signals})}catch(e){setError(e.message||'Unable to load business workspace.')}finally{setLoading(false)}}
 useEffect(()=>{if(authenticated)load();else if(!authLoading)setLoading(false)},[authenticated,authLoading]);
 async function toggleQr(q){setQrBusy(q.id);try{await setQrActive(active,q.id,!q.active);await load(active)}catch(e){setError(e.message||'Unable to update QR status.')}finally{setQrBusy(null)}}
 async function runSignal(s){if(!s?.action)return;setActionBusy(s.key);setMessage('');try{await executeIntelligenceAction(active,s);setMessage(`${actionLabel(s.action)} created successfully.`);await load(active)}catch(e){setMessage(e.message||'Unable to execute intelligence action.')}finally{setActionBusy(null)}}
 if(authLoading||loading)return <section className="page"><div className="empty-state"><p>Loading business workspace…</p></div></section>;
 if(!authenticated)return <section className="page"><div className="empty-state"><h2>Sign in to access the business console</h2><Link className="primary" to="/profile">Sign in</Link></div></section>;
 if(params.get('manage')==='1')return <BusinessManagePage/>;
 if(error)return <section className="page"><div className="empty-state"><h2>Business workspace unavailable</h2><p>{error}</p><button className="secondary" onClick={()=>load(active)}><RefreshCw size={16}/>Retry</button></div></section>;
 if(!data.businesses.length)return <section className="page"><div className="business-hero"><span className="eyebrow">KLEENEST FOR BUSINESS</span><h1>Turn your location into a <em>living profile.</em></h1><p>No managed business is connected to this account yet.</p><Link className="primary" to="/business">Start business setup</Link></div></section>;
 const business=data.businesses.find(b=>b.id===active)||data.businesses[0],a=data.analytics||{},r=data.reviews||{},l=data.lifecycle||{},f=l.funnel||{};
 return <section className="page business-page"><div className="page-header"><div><span className="eyebrow">BUSINESS COMMAND CENTER</span><h1>{business.name||'Your business'}</h1><p>Manage locations, QR check-ins, reputation, and local demand from one place.</p></div><div className="hero-actions"><Link className="primary" to="/business/dashboard?manage=1">Manage business</Link><button className="secondary" onClick={()=>load(active)}><RefreshCw size={16}/>Refresh</button></div></div><FeatureNavLinks business/>
 {data.businesses.length>1&&<div className="business-switcher">{data.businesses.map(b=><button key={b.id} className={b.id===business.id?'selected':''} onClick={()=>load(b.id)}>{b.name}</button>)}</div>}
 <div className="business-stat-grid"><div><Building2/><strong>{data.locations.length}</strong><span>managed locations</span></div><div><QrCode/><strong>{data.qrs.length}</strong><span>QR codes</span></div><div><BarChart3/><strong>{a.check_ins??a.total_check_ins??0}</strong><span>check-ins</span></div><div><span>🏆</span><strong>{a.reward_points??0}</strong><span>reward points</span></div><div><Star/><strong>{Number(r.average_rating??r.avg_rating??0).toFixed(1)}</strong><span>review rating</span></div></div>
 <div className="business-grid"><Card><div className="panel-heading"><div><span className="eyebrow">LOCATIONS</span><h2>Location network</h2></div></div>{data.locations.map(x=><div className="business-row" key={x.id}><div><strong>{x.name}</strong><span>{[x.city,x.state].filter(Boolean).join(', ')||x.address||'Address not set'}</span></div></div>)}</Card><Card><div className="panel-heading"><div><span className="eyebrow">QR LIFECYCLE</span><h2>Check-in codes</h2></div></div>{data.qrs.length?data.qrs.map(q=><div className="business-row" key={q.id}><div><strong>{q.label||'Kleenest QR'}</strong><span>{q.active?'Active':'Inactive'} · {q.purpose||'checkin'}</span></div><button className="icon-button" disabled={qrBusy===q.id} onClick={()=>toggleQr(q)}>{q.active?<ToggleRight/>:<ToggleLeft/>}</button></div>):<p className="observation-copy">No QR codes have been created.</p>}</Card></div>
 <Card><div className="panel-heading"><div><span className="eyebrow">INTELLIGENCE ACTIONS</span><h2>Act on what the network is telling you</h2></div><ShieldCheck size={22}/></div>{message&&<p className="form-success">{message}</p>}{data.signals.filter(s=>s.action).length?data.signals.filter(s=>s.action).slice(0,8).map(s=><div className="business-row" key={s.key}><div><strong>{s.title}</strong><span>{s.evidence}</span><span>{s.priority.toUpperCase()} priority</span></div><button className="secondary" disabled={actionBusy===s.key} onClick={()=>runSignal(s)}>{actionBusy===s.key?'Working…':actionLabel(s.action)}</button></div>):<p className="observation-copy">No executable opportunity is currently indicated.</p>}</Card>
 <Card><div className="panel-heading"><div><span className="eyebrow">LOCATION INTELLIGENCE</span><h2>Demand, quality & activity</h2></div><ShieldCheck size={22}/></div>{data.intelligence.length?data.intelligence.slice(0,12).map(row=>{const trust=trustSummary(row);return <div className="business-row" key={row.location_id}><div><strong>{row.name}</strong><span>Demand: {n(row.searches)} searches · {n(row.directions)} directions · {n(row.check_ins)} check-ins · {n(row.reviews)} reviews</span><span>{trust.label}{row.freshness_label?` · ${row.freshness_label}`:''}</span></div><div className="business-intelligence-score"><strong>{n(row.intelligence_score)}</strong><span>{intelligenceLabel(row.intelligence_score)}</span></div></div>}):<p className="observation-copy">No location intelligence has accumulated yet.</p>}</Card>
 <Card><div className="panel-heading"><div><span className="eyebrow">LIFECYCLE ANALYTICS</span><h2>Engagement funnel</h2></div><BarChart3 size={22}/></div>{data.lifecycle?<div className="business-insights"><div><strong>{firstNumber(f,['impressions','views','discoveries'])}</strong><span>discoveries / views</span></div><div><strong>{firstNumber(f,['engagements','engagement'])}</strong><span>engagements</span></div><div><strong>{firstNumber(f,['check_ins','checkIns','visits'])}</strong><span>check-ins / visits</span></div></div>:<p className="observation-copy">Advanced lifecycle analytics unavailable.</p>}</Card>
 <div className="business-grid"><Card><h2>Campaigns</h2><p>{data.campaigns.length} active records</p></Card><Card><h2>Promotions</h2><p>{data.promotions.length} active records</p></Card><Card><h2>Contests</h2><p>{data.contests.length} records</p></Card><Card><h2>Events</h2><p>{data.events.length} records</p></Card></div></section>;
}
