import { useEffect,useState } from 'react';
import { Power,QrCode,Plus,BarChart3,MessageSquare } from 'lucide-react';
import { listBusinesses,listLocations,createLocation,createQr,setQrActive,getAnalytics,getReviewAnalytics } from '../services/business';
import { listBusinessQrs } from '../services/qr';
import { useAuth } from '../context/AuthContext';

export default function BusinessDashboard(){
 const {authenticated}=useAuth(); const [businesses,setBusinesses]=useState([]),[selected,setSelected]=useState(null),[locations,setLocations]=useState([]),[qrs,setQrs]=useState([]),[analytics,setAnalytics]=useState(null),[reviewAnalytics,setReviewAnalytics]=useState(null),[message,setMessage]=useState(''),[form,setForm]=useState({name:'',address:'',city:'',state:'',postalCode:''});
 async function load(b){setSelected(b);try{const [l,q,a,r]=await Promise.all([listLocations(b.id),listBusinessQrs(),getAnalytics(b.id),getReviewAnalytics(b.id)]);setLocations(l||[]);setQrs(q||[]);setAnalytics(a);setReviewAnalytics(r)}catch(e){setMessage(e.message||'Unable to load business data.')}}
 useEffect(()=>{if(authenticated)listBusinesses().then(x=>{const b=Array.isArray(x)?x:(x?.businesses||[]);setBusinesses(b);if(b[0])load(b[0])}).catch(e=>setMessage(e.message||'Unable to load businesses.'))},[authenticated]);
 async function addLocation(e){e.preventDefault();try{await createLocation(selected.id,form);setForm({name:'',address:'',city:'',state:'',postalCode:''});await load(selected);setMessage('Location added.')}catch(e){setMessage(e.message||'Unable to add location.')}}
 async function addQr(locationId){try{await createQr(selected.id,locationId,{label:'Kleenest Check-in',purpose:'checkin',actionType:'checkin'});await load(selected);setMessage('QR created.')}catch(e){setMessage(e.message||'Unable to create QR.')}}
 async function toggle(q){try{await setQrActive(selected.id,q.id,!q.active);await load(selected)}catch(e){setMessage(e.message||'Unable to update QR.')}}
 if(!authenticated)return <section className="page"><div className="empty-state"><h2>Business dashboard</h2><p>Sign in with your business account to continue.</p></div></section>;
 return <section className="page"><div className="page-header"><div><span className="eyebrow">BUSINESS WORKSPACE</span><h1>Business dashboard</h1><p>Manage locations, QR check-ins and performance from the same Supabase contracts.</p></div></div>{businesses.length>1&&<div className="filters">{businesses.map(b=><button className={selected?.id===b.id?'selected':''} key={b.id} onClick={()=>load(b)}>{b.name}</button>)}</div>}{selected&&<><div className="business-stats"><div><BarChart3/><strong>{analytics?.total_check_ins??analytics?.check_ins??0}</strong><span>Check-ins</span></div><div><MessageSquare/><strong>{reviewAnalytics?.total_reviews??reviewAnalytics?.reviews??0}</strong><span>Reviews</span></div><div><QrCode/><strong>{qrs.length}</strong><span>QR codes</span></div></div><div className="business-grid"><section className="detail-panel"><h2>Locations</h2>{locations.map(l=><div className="business-row" key={l.id}><div><strong>{l.name}</strong><span>{[l.address,l.city,l.state].filter(Boolean).join(', ')}</span></div><button className="secondary" onClick={()=>addQr(l.id)}><QrCode size={16}/>Create QR</button></div>)}<form className="business-form" onSubmit={addLocation}><h3><Plus size={17}/>Add location</h3>{Object.keys(form).map(k=><input key={k} required={k==='name'} placeholder={k.replace(/([A-Z])/g,' $1')} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<button className="primary">Add location</button></form></section><section className="detail-panel"><h2>QR management</h2>{qrs.length?qrs.map(q=><div className="business-row" key={q.id}><div><strong>{q.label||'Check-in QR'}</strong><span>{q.code} · {q.active?'Active':'Inactive'} · {q.single_use?'Single use':'Reusable'}</span></div><button className="secondary" onClick={()=>toggle(q)}><Power size={16}/>{q.active?'Deactivate':'Activate'}</button></div>):<p>No QR codes yet.</p>}</section></div></>}{message&&<p className="form-success">{message}</p>}</section>;
}
