import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {CheckCircle2,RefreshCw,Trophy,Medal,Send} from 'lucide-react';
import {listActiveContests,joinContest,submitContestEntry,getContestScore,getUserLeaderboard} from '../services/contests';
import {useAuth} from '../context/AuthContext';

export default function ContestsPage(){
 const {authenticated,profile}=useAuth();
 const [contests,setContests]=useState([]),[leaders,setLeaders]=useState([]),[scores,setScores]=useState({}),[joined,setJoined]=useState({}),[entries,setEntries]=useState({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[message,setMessage]=useState(''),[error,setError]=useState(null);
 async function load(){setLoading(true);setError(null);try{const [active,leaderboard]=await Promise.all([listActiveContests(),getUserLeaderboard()]);const rows=active||[];setContests(rows);setLeaders(leaderboard||[]);if(profile?.id){const pairs=await Promise.all(rows.map(async c=>{try{return [c.id,await getContestScore(c.id,profile.id)]}catch{return [c.id,null]}}));const nextScores=Object.fromEntries(pairs);setScores(nextScores);setJoined(Object.fromEntries(pairs.filter(([,score])=>Boolean(score)).map(([id])=>[id,true])));}}catch(e){setError(e.message||'Unable to load contests.')}finally{setLoading(false)}}
 useEffect(()=>{if(authenticated)load();else setLoading(false)},[authenticated,profile?.id]);
 async function join(id){setBusy(`join-${id}`);setMessage('');try{await joinContest(id);setJoined(v=>({...v,[id]:true}));setMessage('You joined the contest.');await load()}catch(e){setMessage(e.message||'Unable to join contest.')}finally{setBusy(null)}}
 async function submit(id){const text=String(entries[id]||'').trim();if(!text)return;setBusy(`submit-${id}`);setMessage('');try{await submitContestEntry(id,{description:text});setEntries(v=>({...v,[id]:''}));setMessage('Entry submitted. Your contest score will update when the contribution is evaluated.');await load();window.dispatchEvent(new CustomEvent('kleenest:rewards-updated'))}catch(e){setMessage(e.message||'Unable to submit entry.')}finally{setBusy(null)}}
 if(!authenticated)return <section className="page"><div className="empty-state"><h2>Sign in to join contests</h2><p>Community challenges, scores, and rewards are tied to your Kleenest account.</p><Link className="primary" to="/profile">Sign in</Link></div></section>;
 if(error)return <section className="page"><div className="empty-state"><h2>Contests unavailable</h2><p>{error}</p><button className="secondary" onClick={load}><RefreshCw size={16}/>Retry</button></div></section>;
 if(loading)return <section className="page"><div className="empty-state">Loading community challenges…</div></section>;
 return <section className="page"><div className="page-header"><div><span className="eyebrow">COMMUNITY CHALLENGES</span><h1>Contests</h1><p>Join local challenges, contribute verified activity, and build your community standing.</p></div><div className="hero-actions"><Link className="secondary" to="/rewards"><Trophy size={16}/>Rewards</Link><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div></div>
 {message&&<p className="form-success">{message}</p>}
 <div className="business-grid"><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">ACTIVE</span><h2>Current challenges</h2></div><Trophy size={22}/></div>{contests.length?contests.map(c=>{const score=scores[c.id],isJoined=joined[c.id]||Boolean(score);return <article className="contest-card" key={c.id}><div className="panel-heading"><div><strong>{c.name||c.title||'Kleenest challenge'}</strong><span>{c.description||'Complete verified community activity to participate.'}</span></div>{isJoined&&<CheckCircle2 size={20}/>}</div><div className="meta"><span>{c.starts_at?new Date(c.starts_at).toLocaleDateString():''}</span>{c.ends_at&&<span>→ {new Date(c.ends_at).toLocaleDateString()}</span>}{score&&<span>Score: {score.score??score.points??0}</span>}</div><div className="hero-actions"><button className="primary" disabled={busy===`join-${c.id}`||isJoined} onClick={()=>join(c.id)}>{isJoined?'Joined':busy===`join-${c.id}`?'Joining…':'Join contest'}</button>{isJoined&&<div className="contest-entry"><input value={entries[c.id]||''} onChange={e=>setEntries(v=>({...v,[c.id]:e.target.value}))} placeholder="Describe your contest contribution"/><button className="secondary" disabled={busy===`submit-${c.id}`||!String(entries[c.id]||'').trim()} onClick={()=>submit(c.id)}><Send size={16}/>{busy===`submit-${c.id}`?'Submitting…':'Submit entry'}</button></div>}</div></article>}) : <div className="empty-state"><h3>No active contests</h3><p>When businesses publish community challenges, they'll appear here.</p></div>}</section><aside className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">LEADERBOARD</span><h2>Community leaders</h2></div><Medal size={22}/></div>{leaders.length?leaders.slice(0,10).map((row,i)=><div className="reward-row" key={row.user_id||row.id||i}><div><strong>#{i+1} {row.display_name||row.name||'Kleenest member'}</strong><span>{row.level!=null?`Level ${row.level} · `:''}{row.total_check_ins??row.check_ins??0} check-ins</span></div><b>{row.points??row.total_points??0}</b></div>):<p>No leaderboard data yet.</p>}</aside></div></section>;
}
