import { useEffect,useMemo,useState } from 'react';
import { Activity, BarChart3, Building2, ChevronRight, MapPinned, RefreshCw, ShieldCheck, Users, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { listBusinesses, listLocations, getAnalytics, getReviewAnalytics } from '../services/business';
import { getBusinessIntelligence } from '../services/intelligence';
import { useAuth } from '../context/AuthContext';
import { hasCapability } from '../domain/capabilities';
import '../styles/enterprise-command.css';

const arr=value=>Array.isArray(value)?value:[];

export default function EnterpriseCommandCenterPage(){
 const {authenticated,loading:authLoading,capabilities}=useAuth();
 const [businesses,setBusinesses]=useState([]); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(null);
 const authorized=hasCapability(capabilities,'admin')||hasCapability(capabilities,'business')||hasCapability(capabilities,'enterprise');
 async function load(){setLoading(true);setError(null);try{const list=arr(await listBusinesses());setBusinesses(list);const selected=list.filter(b=>String(b.plan||b.plan_key||b.subscription_plan||'').toLowerCase()==='enterprise'||b.is_enterprise);const source=selected.length?selected:list;const next=await Promise.all(source.slice(0,25).map(async business=>{const [locations,analytics,reviews,intelligence]=await Promise.allSettled([listLocations(business.id),getAnalytics(business.id),getReviewAnalytics(business.id),getBusinessIntelligence(business.id)]);const locs=locations.status==='fulfilled'?arr(locations.value):[];const a=analytics.status==='fulfilled'?(analytics.value||{}):{};const r=reviews.status==='fulfilled'?(reviews.value||{}):{};const signals=intelligence.status==='fulfilled'?arr(intelligence.value?.signals):[];return {business,locations:locs,analytics:a,reviews:r,signals}}));setRows(next);}catch(e){setError(e?.message||'Unable to load enterprise command center.')}finally{setLoading(false)}}
 useEffect(()=>{if(authenticated&&authorized)load();else if(!authLoading)setLoading(false)},[authenticated,authLoading,authorized]);
 const totals=useMemo(()=>rows.reduce((s,row)=>{s.locations+=row.locations.length;s.checkins+=Number(row.analytics.check_ins??row.analytics.total_check_ins??0);s.reviews+=Number(row.reviews.total_reviews??row.reviews.review_count??0);s.opportunities+=row.signals.filter(x=>x?.action||Number(x?.priority_score||0)>=60).length;return s},{locations:0,checkins:0,reviews:0,opportunities:0}),[rows]);
 if(authLoading||loading)return <section className="page"><div className="empty-state loading-state"><span className="loading-dot"/><div><strong>Loading enterprise command center</strong><p>Aggregating locations, activity, reputation, and intelligence…</p></div></div></section>;
 if(!authenticated)return <section className="page"><div className="empty-state"><h2>Sign in to access Enterprise</h2><Link className="primary" to="/profile">Sign in</Link></div></section>;
 if(!authorized)return <section className="page"><div className="empty-state"><ShieldCheck size={38}/><h2>Enterprise access required</h2><p>This command center is limited to business, enterprise, and administrator accounts.</p><Link className="secondary" to="/business/dashboard">Business dashboard</Link></div></section>;
 if(error)return <section className="page"><div className="empty-state"><h2>Enterprise command center unavailable</h2><p>{error}</p><button className="secondary" onClick={load}><RefreshCw size={16}/>Retry</button></div></section>;
 return <section className="page enterprise-page"><div className="enterprise-hero"><div><span className="eyebrow">KLEENEST ENTERPRISE</span><h1>Command center</h1><p>One operational view across managed locations, customer activity, reputation, and intelligence opportunities.</p></div><div className="hero-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh network</button><Link className="primary" to="/map"><MapPinned size={17}/>Open network map</Link></div></div><div className="enterprise-metrics"><div><Building2 size={18}/><strong>{rows.length}</strong><span>managed organizations</span></div><div><MapPinned size={18}/><strong>{totals.locations}</strong><span>locations</span></div><div><Users size={18}/><strong>{totals.checkins}</strong><span>check-ins</span></div><div><Activity size={18}/><strong>{totals.reviews}</strong><span>reviews</span></div><div><Zap size={18}/><strong>{totals.opportunities}</strong><span>action opportunities</span></div></div><div className="enterprise-toolbar"><div><span className="eyebrow">OPERATIONS</span><h2>Portfolio control</h2></div><div className="enterprise-links"><Link to="/business/dashboard">Business command <ChevronRight size={15}/></Link><Link to="/fleet">Fleet operations <ChevronRight size={15}/></Link><Link to="/business/performance">Performance <ChevronRight size={15}/></Link><Link to="/admin/data">Data operations <ChevronRight size={15}/></Link></div></div><div className="enterprise-grid">{rows.length?rows.map(row=><article className="enterprise-card" key={row.business.id}><div className="enterprise-card-head"><div><span className="eyebrow">ORGANIZATION</span><h3>{row.business.name}</h3><span>{row.business.city||row.business.address||'Managed Kleenest organization'}</span></div><Building2 size={22}/></div><div className="enterprise-card-metrics"><div><strong>{row.locations.length}</strong><span>locations</span></div><div><strong>{row.analytics.check_ins??row.analytics.total_check_ins??0}</strong><span>check-ins</span></div><div><strong>{row.reviews.average_rating!=null?Number(row.reviews.average_rating).toFixed(1):'—'}</strong><span>rating</span></div><div><strong>{row.signals.length}</strong><span>signals</span></div></div><div className="enterprise-card-actions"><Link className="secondary" to={`/business/dashboard?business=${encodeURIComponent(row.business.id)}`}>Open business</Link><Link className="secondary" to="/business/intelligence"><Zap size={15}/>Intelligence</Link><Link className="secondary" to="/fleet"><Activity size={15}/>Fleet</Link></div></article>):<div className="empty-state enterprise-empty"><BarChart3 size={36}/><h2>No managed organizations found</h2><p>Connect a business account to populate the enterprise portfolio.</p><Link className="primary" to="/business/dashboard">Open business setup</Link></div>}</div></section>;
}
