import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, MapPinned, Navigation, Radio, RefreshCw, Route as RouteIcon, ShieldCheck, Target, Users } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { listPlaces } from '../services/places';
import { getLocationSignals } from '../services/intelligence';
import { buildFleetRecommendations } from '../services/intelligenceRecommendations';
import { subscribeToLiveEvents } from '../services/liveNetwork';
import { useAuth } from '../context/AuthContext';
import { hasCapability } from '../domain/capabilities';
import '../styles/admin-fleet.css';

const asArray=value=>{if(Array.isArray(value))return value;if(!value||typeof value!=='object')return[];for(const key of ['rows','items','places','locations','signals','recommendations','data'])if(Array.isArray(value[key]))return value[key];return Object.values(value).filter(v=>v&&typeof v==='object'&&!Array.isArray(v));};
const safeSignals=value=>asArray(value).filter(Boolean);

export default function FleetReviewPage(){
 const {authenticated,loading:authLoading,capabilities}=useAuth(); const [params]=useSearchParams();
 const [state,setState]=useState({places:[],signals:[],live:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(null); const [livePulse,setLivePulse]=useState(null);
 const fleetAuthorized=hasCapability(capabilities,'fleet')||hasCapability(capabilities,'admin');
 async function load(){setLoading(true);setError(null);try{
  const placeResult=await listPlaces({category:'restroom',sort:'recommended',limit:60});
  const places=asArray(placeResult); const rows=places.filter(p=>p?.location_id||p?.id).slice(0,30);
  const enriched=await Promise.all(rows.map(async place=>{try{const result=await getLocationSignals(place.location_id||place.id,{liveEventLimit:50});return {...place,signals:result?.signals||{},liveEvents:asArray(result?.liveEvents)}}catch{return {...place,signals:{demand_score:0,activity_score:0,quality_score:Number(place.intelligence_score||0),operational_status:'normal',recent_event_count:0,recent_arrivals:0,recent_checkins:0},liveEvents:[]}}}));
  const signals=enriched.map(row=>({location_id:row.location_id||row.id,name:row.name,...(row.signals||{})}));setState({places:enriched,signals:safeSignals(signals),live:enriched.flatMap(row=>asArray(row.liveEvents))});
 }catch(e){setError(e?.message||'Unable to load Fleet network intelligence.')}finally{setLoading(false)}}
 useEffect(()=>{if(authenticated&&fleetAuthorized)load();else if(!authLoading)setLoading(false)},[authenticated,authLoading,fleetAuthorized]);
 useEffect(()=>{if(!authenticated||!fleetAuthorized)return undefined;let timer;const refresh=()=>{clearTimeout(timer);timer=setTimeout(load,500)};window.addEventListener('kleenest:location-activity',refresh);window.addEventListener('kleenest:intelligence-updated',refresh);let unsubscribe;try{unsubscribe=subscribeToLiveEvents({onEvent:event=>{if(String(event?.event_type||'').startsWith('fleet.')||String(event?.event_type||'').startsWith('location.')){setLivePulse(event);refresh()}}})}catch{}return()=>{clearTimeout(timer);window.removeEventListener('kleenest:location-activity',refresh);window.removeEventListener('kleenest:intelligence-updated',refresh);unsubscribe?.()}},[authenticated,fleetAuthorized]);
 const recommendations=useMemo(()=>asArray(buildFleetRecommendations(state.signals)),[state.signals]); const requested=params.get('location'); const selected=recommendations.find(item=>String(item.location_id)===String(requested));
 const attention=state.signals.filter(x=>x.operational_status==='attention'||x.operational_status==='stale'); const active=state.signals.filter(x=>Number(x.activity_score||0)>=40||Number(x.recent_event_count||0)>0); const avgQuality=state.signals.length?Math.round(state.signals.reduce((s,x)=>s+Number(x.quality_score||0),0)/state.signals.length):0;
 function openRoute(item){const location=state.places.find(row=>String(row.location_id||row.id)===String(item.location_id));if(!location)return;const destination=location.latitude!=null&&location.longitude!=null?`${location.latitude},${location.longitude}`:[location.address,location.city,location.state].filter(Boolean).join(', ');if(destination)window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destination)}`,'_blank','noopener,noreferrer')}
 if(authLoading||loading)return <section className="page"><div className="empty-state loading-state"><span className="loading-dot"/><div><strong>Loading Fleet network intelligence</strong><p>Finding high-value waypoints and service signals…</p></div></div></section>;
 if(!authenticated)return <section className="page"><div className="empty-state"><h2>Sign in to access Fleet</h2><Link className="primary" to="/profile">Sign in</Link></div></section>;
 if(!fleetAuthorized)return <section className="page"><div className="empty-state"><ShieldCheck size={38}/><h2>Fleet access required</h2><p>This operational surface is limited to Fleet and administrator accounts.</p><Link className="secondary" to="/">Return home</Link></div></section>;
 if(error)return <section className="page"><div className="empty-state"><AlertTriangle size={36}/><h2>Fleet network unavailable</h2><p>{error}</p><button className="secondary" onClick={load}><RefreshCw size={16}/>Retry network</button></div></section>;
 return <section className="page business-page fleet-page"><div className="page-header"><div><span className="eyebrow">KLEENEST FLEET</span><h1>Network operations</h1><p>Use the broader Kleenest network to find better restroom stops, service opportunities, and live operational signals.</p></div><div className="hero-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh network</button><Link className="secondary" to="/map"><MapPinned size={16}/>Open network map</Link></div></div>
 {livePulse&&<div className="success-banner"><Radio size={16}/><span>Live network signal: <strong>{livePulse.event_type}</strong></span></div>}
 <div className="fleet-metric-strip"><div className="fleet-metric"><MapPinned size={18}/><strong>{state.places.length}</strong><span>network stops</span></div><div className="fleet-metric"><Target size={18}/><strong>{recommendations.length}</strong><span>service opportunities</span></div><div className="fleet-metric"><AlertTriangle size={18}/><strong>{attention.length}</strong><span>attention signals</span></div><div className="fleet-metric"><Activity size={18}/><strong>{avgQuality}</strong><span>network confidence</span></div></div>
 <div className="business-grid">
  <section className="detail-panel business-card"><div className="panel-heading"><div><span className="eyebrow">ROUTE OPERATIONS</span><h2>Priority service waypoints</h2></div><RouteIcon size={22}/></div>{selected&&<div className="business-action-row"><div><strong>{selected.name}</strong><span>{selected.recommendation.body}</span></div><button className="primary" onClick={()=>openRoute(selected)}><Navigation size={16}/>Open route</button></div>}<div className="business-intelligence-list">{recommendations.length?recommendations.slice(0,10).map(item=><div className={`business-row ${requested===String(item.location_id)?'selected':''}`} key={item.location_id}><div><strong>{item.name}</strong><span>{item.recommendation.body}</span><span>Demand {item.signals.demand_score} · Activity {item.signals.activity_score} · Quality {item.signals.quality_score}</span></div><div className="business-intelligence-score"><Target size={16}/><Link className="secondary" to={`/fleet?location=${encodeURIComponent(item.location_id)}`}>Inspect</Link><button className="secondary" onClick={()=>openRoute(item)}><Navigation size={14}/>Route</button></div></div>):<p className="observation-copy">No elevated service opportunities are currently detected.</p>}</div></section>
  <section className="detail-panel business-card"><div className="panel-heading"><div><span className="eyebrow">SERVICE HEALTH</span><h2>Network issues</h2></div><ShieldCheck size={22}/></div>{attention.length?attention.slice(0,8).map(row=><div className="business-row" key={row.location_id}><div><strong>{row.name}</strong><span>{row.operational_status==='stale'?'Stale signal':'Conflicting signal'} · Confidence {row.quality_score}</span></div><span className="tag">Follow up</span></div>):<div className="business-action-row"><CheckCircle2 size={20}/><div><strong>Network looks healthy</strong><span>No stale or conflicting signals are currently elevated.</span></div></div>}</section>
 </div>
 <section className="detail-panel business-card"><div className="panel-heading"><div><span className="eyebrow">LIVE NETWORK</span><h2>Fleet-relevant activity</h2></div><Users size={22}/></div>{active.length?active.slice(0,10).map(row=><div className="business-row" key={row.location_id}><div><strong>{row.name}</strong><span>{row.recent_event_count||0} recent events · {row.recent_arrivals||0} arrivals · {row.recent_checkins||0} check-ins</span></div><span className="tag">{row.operational_status}</span></div>):<p className="observation-copy">No elevated activity yet. The network keeps monitoring.</p>}</section>
 <section className="detail-panel business-card"><div className="panel-heading"><div><span className="eyebrow">NETWORK STOPS</span><h2>Nearby restroom intelligence</h2></div><MapPinned size={22}/></div>{state.places.length?state.places.slice(0,8).map(place=><div className="business-row" key={place.id}><div><strong>{place.name}</strong><span>{place.address||'Address not set'}</span><span>{place.freshness_label||'Network observation'}{place.distance_miles!=null?` · ${place.distance_miles.toFixed(1)} mi`:''}</span></div><Link className="secondary" to={`/place/${place.id}`}>Review stop</Link></div>):<p className="observation-copy">No network restroom stops are available.</p>}</section>
 </section>;
}
