import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Brain,Clock3,Gamepad2,RotateCcw,Trophy,Zap} from 'lucide-react';
import {Link} from 'react-router-dom';
import FeatureNavLinks from '../components/FeatureNavLinks';
import {useAuth} from '../context/AuthContext';

const games=[
 {id:'tap',title:'Clean Sweep',tag:'30 seconds',icon:Zap,description:'Find the clean tiles and build a streak.',color:'sun'},
 {id:'memory',title:'Bathroom Memory',tag:'Quick match',icon:Brain,description:'Match amenity pairs in as few moves as possible.',color:'mint'},
 {id:'quiz',title:'Kleenest Quick Quiz',tag:'5 questions',icon:Trophy,description:'Test your knowledge of places and community trust.',color:'sky'}
];
const memorySymbols=['WC','♨','★','♧'];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);

export default function GamesPage(){
 const{authenticated}=useAuth();
 const [active,setActive]=useState(null),[score,setScore]=useState(0),[round,setRound]=useState(0),[message,setMessage]=useState('Pick a quick game.'),[targets,setTargets]=useState([]),[matched,setMatched]=useState([]),[choice,setChoice]=useState([]),[quizIndex,setQuizIndex]=useState(0);
 const tapTargets=useMemo(()=>shuffle(Array.from({length:12},(_,i)=>i)).slice(0,5),[active]);
 useEffect(()=>{if(active==='memory'){setTargets(shuffle([...memorySymbols,...memorySymbols]));setMatched([]);setChoice([])}setScore(0);setRound(0);setQuizIndex(0)},[active]);
 function tap(i){setRound(r=>r+1);if(tapTargets.includes(i)){setScore(s=>s+10);setMessage('Clean! +10')}else setMessage('Not this one — keep sweeping.')}
 function memory(i){if(choice.length===2||matched.includes(i)||choice.includes(i))return;const next=[...choice,i];setChoice(next);if(next.length===2){setRound(r=>r+1);if(targets[next[0]]===targets[next[1]]){setMatched(m=>[...m,...next]);setScore(s=>s+20);setMessage('Perfect match! +20')}else setMessage('No match — try again.');window.setTimeout(()=>setChoice([]),450)}}
 function answer(i){const correct=[0,2,1,0,2][quizIndex];setRound(r=>r+1);if(i===correct){setScore(s=>s+15);setMessage('Correct! +15')}else setMessage('Not quite. Keep going.');if(quizIndex<4)window.setTimeout(()=>setQuizIndex(x=>x+1),500);else setMessage(i===correct?'Quiz complete! +15':'Quiz complete!')}
 if(!authenticated)return <section className="page"><Link className="back-link" to="/profile"><ArrowLeft size={16}/>Back to profile</Link><div className="empty-state"><h2>Sign in to play</h2><p>Your play progress can become part of your Kleenest profile.</p><Link className="primary" to="/profile">Sign in</Link></div></section>;
 return <section className="page games-page"><Link className="back-link" to="/rewards"><ArrowLeft size={16}/>Back to rewards</Link><div className="page-header"><div><span className="eyebrow">KLEENEST PLAY</span><h1>Something fun while you're here</h1><p>Small, free games for a quick bathroom break. No ads required.</p></div><div className="reward-stats"><div><Gamepad2/><strong>{score}</strong><span>score</span></div><div><Zap/><strong>{round}</strong><span>moves</span></div></div></div><FeatureNavLinks/><div className="game-grid">{games.map(g=>{const Icon=g.icon;return <button className={`game-card game-${g.color} ${active===g.id?'selected':''}`} key={g.id} onClick={()=>{setActive(g.id);setMessage('Ready!')}}><span className="game-icon"><Icon/></span><span><b>{g.title}</b><small>{g.tag}</small><em>{g.description}</em></span></button>})}</div>{active&&<section className="detail-panel game-board"><div className="panel-heading"><div><span className="eyebrow">NOW PLAYING</span><h2>{games.find(g=>g.id===active)?.title}</h2></div><Clock3 size={24}/></div><p className="game-message">{message}</p>{active==='tap'&&<div className="tap-board">{Array.from({length:12},(_,i)=><button key={i} onClick={()=>tap(i)} aria-label={`tile ${i+1}`}>{tapTargets.includes(i)?'✓':'·'}</button>)}</div>}{active==='memory'&&<div className="memory-board">{targets.map((symbol,i)=><button key={i} className={matched.includes(i)?'matched':''} onClick={()=>memory(i)} aria-label={`memory card ${i+1}`}>{matched.includes(i)||choice.includes(i)?symbol:'?'}</button>)}</div>}{active==='quiz'&&<div className="quiz-board"><h3>{['Which action creates the strongest community signal?','What makes a location more trustworthy?','What should a useful bathroom review include?','What can a business learn from network activity?','What earns contributor progress?'][quizIndex]}</h3>{[['A verified check-in','A random tap','Ignoring location details'],['Fresh verified observations','Old guesses','Nothing'],['Useful firsthand details','Only a star','Nothing'],['Demand and location signals','Nothing','Only ads'],['Verified contributions','Doing nothing','Leaving the app']][quizIndex].map((x,i)=><button key={x} onClick={()=>answer(i)}>{x}</button>)}</div>}<button className="secondary" onClick={()=>{setActive(null);setMessage('Pick a quick game.')}}><RotateCcw size={16}/>Choose another</button></section>}</section>
}
