import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Brain,Clock3,Gamepad2,RotateCcw,Trophy,Zap,Grid3X3,Target,Shuffle} from 'lucide-react';
import {Link} from 'react-router-dom';
import FeatureNavLinks from '../components/FeatureNavLinks';
import {useAuth} from '../context/AuthContext';
import {recordGameScore} from '../services/rewards';
import '../styles/games.css';
const games=[
{id:'tap',title:'Clean Sweep',tag:'30 seconds',icon:Zap,description:'Find the clean tiles and build a streak.',color:'sun'},
{id:'memory',title:'Bathroom Memory',tag:'Quick match',icon:Brain,description:'Match amenity pairs in as few moves as possible.',color:'mint'},
{id:'quiz',title:'Kleenest Quick Quiz',tag:'5 questions',icon:Trophy,description:'Test your knowledge of places and community trust.',color:'sky'},
{id:'word',title:'Bathroom Word Mix',tag:'Unscramble',icon:Shuffle,description:'Unscramble a bathroom word before time runs out.',color:'violet'},
{id:'target',title:'Flush the Facts',tag:'Rapid fire',icon:Target,description:'Hit the correct answer and keep your streak alive.',color:'rose'},
{id:'grid',title:'Clean Grid',tag:'Pattern memory',icon:Grid3X3,description:'Remember the highlighted pattern and repeat it.',color:'mint'}];
const memorySymbols=['WC','♨','★','♧'];const shuffle=a=>[...a].sort(()=>Math.random()-.5);const words=['RESTROOM','KLEENEST','CHECKIN','CLEAN','TRUST','FRESH'];
export default function GamesPage(){const{authenticated}=useAuth();const[active,setActive]=useState(null),[score,setScore]=useState(0),[round,setRound]=useState(0),[message,setMessage]=useState('Pick a quick game.'),[targets,setTargets]=useState([]),[matched,setMatched]=useState([]),[choice,setChoice]=useState([]),[quizIndex,setQuizIndex]=useState(0),[word,setWord]=useState(''),[wordGuess,setWordGuess]=useState(''),[grid,setGrid]=useState([]),[gridGuess,setGridGuess]=useState([]),[gridSolution,setGridSolution]=useState([]),[saved,setSaved]=useState(false);
const tapTargets=useMemo(()=>shuffle(Array.from({length:12},(_,i)=>i)).slice(0,5),[active]);
useEffect(()=>{setSaved(false);if(active==='memory'){setTargets(shuffle([...memorySymbols,...memorySymbols]));setMatched([]);setChoice([])}if(active==='word'){setWord(shuffle(words[Math.floor(Math.random()*words.length)].split('')).join(''));setWordGuess('')}if(active==='grid'){const s=shuffle(Array.from({length:9},(_,i)=>i)).slice(0,4);setGrid(s);setGridSolution(s);setGridGuess([]);setTimeout(()=>setGrid([]),1100)}setScore(0);setRound(0);setQuizIndex(0);setMessage('Ready!')},[active]);
async function saveScore(){if(saved||!active)return;setSaved(true);try{await recordGameScore({gameId:active,score,rounds:round});setMessage('Score saved to your progression.')}catch(e){setSaved(false);setMessage(e.message||'Score could not be saved.')}}
function tap(i){setRound(r=>r+1);if(tapTargets.includes(i)){setScore(s=>s+10);setMessage('Clean! +10')}else setMessage('Not this one — keep sweeping.')}function chooseMemory(i){if(choice.length===2||matched.includes(i))return;const next=[...choice,i];setChoice(next);setRound(r=>r+1);if(next.length===2){if(targets[next[0]]===targets[next[1]]){setMatched(m=>[...m,...next]);setScore(s=>s+20);setMessage('Match! +20');setChoice([])}else{setMessage('No match — try again.');setTimeout(()=>setChoice([]),500)}}}
const quiz=[['What builds the strongest community signal?',['A verified check-in','A random tap','Skipping location details'],0],['What does a streak reward?',['Consistent contribution','More ads','Nothing'],0],['What can network intelligence connect?',['Places and activity','Only profile photos','Nothing'],0],['Who can see every product surface?',['Admin','Any visitor','Nobody'],0],['What should you do after arriving?',['Share a useful observation','Leave immediately','Ignore the place'],0]];
function answer(i){setRound(r=>r+1);if(i===quiz[quizIndex][2]){setScore(s=>s+15);setMessage('Correct! +15')}else setMessage('Good try.');if(quizIndex<quiz.length-1)setTimeout(()=>setQuizIndex(i=>i+1),450);else setMessage(i===quiz[quizIndex][2]?'Quiz complete!':'Quiz complete!')}function submitWord(){setRound(r=>r+1);if(wordGuess.trim().toUpperCase()===word.split('').sort().join('')){setScore(s=>s+30);setMessage('Unscrambled! +30')}else setMessage('Not quite — try again.')}function targetAnswer(ok){setRound(r=>r+1);setScore(s=>s+(ok?20:0));setMessage(ok?'Bullseye! +20':'Keep going!')}function gridPick(i){if(gridGuess.includes(i)||gridGuess.length>=gridSolution.length)return;const next=[...gridGuess,i];setGridGuess(next);setRound(r=>r+1);if(next.length===gridSolution.length){const good=next.every(x=>gridSolution.includes(x));setScore(s=>s+(good?40:0));setMessage(good?'Pattern matched! +40':'Pattern missed — try again.')}}
if(!authenticated)return <section className="page"><Link className="back-link" to="/profile"><ArrowLeft size={16}/>Back to profile</Link><div className="empty-state"><h2>Sign in to play</h2><p>Your scores and streaks are tied to your Kleenest profile.</p><Link className="primary" to="/profile">Sign in</Link></div></section>;
return <section className="page games-page"><Link className="back-link" to="/rewards"><ArrowLeft size={16}/>Back to rewards</Link><div className="page-header"><div><span className="eyebrow">KLEENEST PLAY</span><h1>Something fun while you're here</h1><p>Small, free games for a quick bathroom break.</p></div><div className="reward-stats"><div><Gamepad2/><strong>{score}</strong><span>score</span></div><div><Zap/><strong>{round}</strong><span>moves</span></div></div></div><FeatureNavLinks/><div className="game-grid">{games.map(g=>{const Icon=g.icon;return <button className={`game-card game-${g.color} ${active===g.id?'selected':''}`} key={g.id} onClick={()=>setActive(g.id)}><span className="game-icon"><Icon/></span><span><b>{g.title}</b><small>{g.tag}</small><em>{g.description}</em></span></button>})}</div>{active&&<section className="detail-panel game-board"><div className="panel-heading"><div><span className="eyebrow">NOW PLAYING</span><h2>{games.find(g=>g.id===active)?.title}</h2></div><Clock3 size={24}/></div><p className="game-message">{message}</p>{active==='tap'&&<div className="tap-board">{Array.from({length:12},(_,i)=><button key={i} onClick={()=>tap(i)}>{tapTargets.includes(i)?'✦':'·'}</button>)}</div>}{active==='memory'&&<div className="memory-board">{targets.map((symbol,i)=><button key={i} onClick={()=>chooseMemory(i)}>{matched.includes(i)||choice.includes(i)?symbol:'?'}</button>)}</div>}{active==='quiz'&&<div className="quiz-board"><h3>{quiz[quizIndex][0]}</h3>{quiz[quizIndex][1].map((x,i)=><button key={x} onClick={()=>answer(i)}>{x}</button>)}</div>}{active==='word'&&<div className="quiz-board"><h3>Unscramble: {word}</h3><input value={wordGuess} onChange={e=>setWordGuess(e.target.value)} placeholder="Type the word"/><button onClick={submitWord}>Submit</button></div>}{active==='target'&&<div className="quiz-board"><h3>Which signal is strongest?</h3><button onClick={()=>targetAnswer(true)}>Verified arrival + useful observation</button><button onClick={()=>targetAnswer(false)}>Random unverified tap</button><button onClick={()=>targetAnswer(false)}>No location context</button></div>}{active==='grid'&&<div className="tap-board">{Array.from({length:9},(_,i)=><button key={i} onClick={()=>gridPick(i)}>{grid.includes(i)&&gridGuess.length===0?'◆':gridGuess.includes(i)?'◆':'·'}</button>)}</div>}<div className="game-actions"><button className="secondary" onClick={saveScore} disabled={saved||round===0}>{saved?'Score saved':'Save score'}</button><button className="secondary" onClick={()=>setActive(null)}><RotateCcw size={16}/>Choose another</button></div></section>}</section>}
