import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Medal,RefreshCw,Trophy,MapPin,Star,Flame,Users} from 'lucide-react';
import {Link} from 'react-router-dom';
import {getUserLeaderboard} from '../services/rewards';
import {useAuth} from '../context/AuthContext';
import '../styles/leaderboard.css';
const boards=[['contributors','Top Contributors',Users],['checkins','Check-in Champions',MapPin],['reviews','Review Leaders',Star],['streaks','Streak Masters',Flame],['points','Point Leaders',Trophy]];
const metric=(r,type)=>type==='checkins'?(r.total_check_ins??r.check_ins??0):type==='reviews'?(r.total_reviews??r.reviews??0):type==='streaks'?(r.streak??r.current_streak??r.longest_streak??0):type==='points'?(r.points??r.total_points??0):((r.points??r.total_points??0)+(r.total_check_ins??r.check_ins??0));
export default function LeaderboardPage(){const{authenticated,loading:authLoading}=useAuth();const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[active,setActive]=useState('contributors');async function load(){setLoading(true);setError('');try{setRows(await getUserLeaderboard())}catch(e){setError(e.message||'Unable to load leaderboard.')}finally{setLoading(false)}}useEffect(()=>{if(authenticated)load();else if(!authLoading)setLoading(false)},[authenticated,authLoading]);const ranked=useMemo(()=>[...rows].sort((a,b)=>metric(b,active)-metric(a,active)).slice(0,50),[rows,active]);if(authLoading)return <section className="page"><div className="empty-state">Checking your session…</div></section>;if(!authenticated)return <section className="page"><div className="empty-state"><h2>Sign in to view leaderboards</h2><Link className="primary" to="/profile">Sign in</Link></div></section>;return <section className="page leaderboard-page"><Link className="back-link" to="/rewards"><ArrowLeft size={16}/>Rewards</Link><div className="page-header"><div><span className="eyebrow">KLEENEST RANKINGS</span><h1>Choose your leaderboard</h1><p>Different ways to contribute. Different ways to become a local legend.</p></div><button className="secondary" onClick={load} disabled={loading}><RefreshCw size={16}/>{loading?'Refreshing…':'Refresh'}</button></div><div className="leaderboard-tabs">{boards.map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><Icon size={17}/><span>{label}</span></button>)}</div>{error?<div className="empty-state"><h2>Leaderboard unavailable</h2><p>{error}</p><button className="secondary" onClick={load}>Retry</button></div>:loading?<div className="empty-state">Loading rankings…</div>:<section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">{boards.find(x=>x[0]===active)?.[1]}</span><h2>Top 50</h2></div><Trophy size={24}/></div>{ranked.length?ranked.map((r,i)=><div className="reward-row" key={r.user_id||r.id||i}><div><strong><Medal size={16}/> #{i+1} {r.display_name||r.name||'Kleenest member'}</strong><span>Level {r.level??1} · {r.total_check_ins??r.check_ins??0} check-ins · {r.total_reviews??r.reviews??0} reviews</span></div><b>{metric(r,active)}</b></div>):<p>No ranking data yet — your first verified contribution can start it.</p>}</section>}</section>}
