import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft,Trophy,Star,RefreshCw,ShieldCheck,CheckCircle2,Medal,Radio,Users,Heart,MessageCircle,UserPlus,UserCheck,Target,Award } from 'lucide-react';
import { getRewardsSummary,getUserLeaderboard } from '../services/rewards';
import { getContributorMilestones,MILESTONE_COPY } from '../services/milestones';
import { followUser,unfollowUser,listFollowing } from '../services/follows';
import { listChallenges,listMyChallengeProgress,listMyBadges,completeProgressionChallenge,evaluateMyBadges } from '../services/progression';
import { supabase } from '../lib/supabase';
import { useAuth } from '../context/AuthContext';
import FeatureNavLinks from '../components/FeatureNavLinks';
import '../styles/social.css';

export default function RewardsPage(){
 const{authenticated,loading:authLoading}=useAuth();
 const[data,setData]=useState(null),[milestones,setMilestones]=useState([]),[leaderboard,setLeaderboard]=useState([]),[social,setSocial]=useState([]),[following,setFollowing]=useState(new Set());
 const[challenges,setChallenges]=useState([]),[challengeProgress,setChallengeProgress]=useState(new Map()),[badges,setBadges]=useState([]),[error,setError]=useState(null),[loading,setLoading]=useState(true),[live,setLive]=useState(false),[followBusy,setFollowBusy]=useState(null),[challengeBusy,setChallengeBusy]=useState(null),[badgeBusy,setBadgeBusy]=useState(false);
 async function load(){
  setLoading(true);setError(null);
  try{
   const[summary,progress,leaders,feed,follows,availableChallenges,myProgress,myBadges]=await Promise.all([
    getRewardsSummary(),getContributorMilestones(),getUserLeaderboard(),
    supabase?.from('reviews').select('id,user_id,stars,comment,created_at,profiles:user_id(display_name),places:location_id(name)').eq('status','published').order('created_at',{ascending:false}).limit(8),
    listFollowing(),listChallenges(),listMyChallengeProgress(),listMyBadges()
   ]);
   if(feed?.error)throw feed.error;
   setData(summary);setMilestones(progress);setLeaderboard(leaders);setSocial(feed?.data||[]);setFollowing(new Set((follows||[]).map(x=>x.following_id)));setChallenges(availableChallenges||[]);
   setChallengeProgress(new Map((myProgress||[]).map(x=>[x.challenge_id,x])));setBadges(myBadges||[]);
  }catch(e){setError(e.message||'Unable to load rewards.')}finally{setLoading(false)}
 }
 useEffect(()=>{if(authenticated)load();else if(!authLoading)setLoading(false)},[authenticated,authLoading]);
 useEffect(()=>{if(!authenticated)return;const handler=()=>{setLive(true);load();window.setTimeout(()=>setLive(false),1800)};window.addEventListener('kleenest:rewards-updated',handler);window.addEventListener('kleenest:location-activity',handler);return()=>{window.removeEventListener('kleenest:rewards-updated',handler);window.removeEventListener('kleenest:location-activity',handler)}},[authenticated]);
 async function toggleFollow(userId){if(!userId||followBusy)return;setFollowBusy(userId);try{if(following.has(userId)){await unfollowUser(userId);setFollowing(prev=>{const next=new Set(prev);next.delete(userId);return next})}else{await followUser(userId);setFollowing(prev=>new Set(prev).add(userId))}}catch(e){setError(e.message||'Unable to update following.')}finally{setFollowBusy(null)}}
 async function completeChallenge(id){if(!id||challengeBusy)return;setChallengeBusy(id);setError(null);try{await completeProgressionChallenge(id);await load()}catch(e){setError(e.message||'Unable to complete challenge.')}finally{setChallengeBusy(null)}}
 async function refreshBadges(){if(badgeBusy)return;setBadgeBusy(true);setError(null);try{await evaluateMyBadges();await load()}catch(e){setError(e.message||'Unable to evaluate badges.')}finally{setBadgeBusy(false)}}
 if(authLoading)return <section className="page"><div className="empty-state">Checking your session…</div></section>;
 if(!authenticated)return <section className="page"><Link className="back-link" to="/profile"><ArrowLeft size={16}/>Back to profile</Link><div className="empty-state"><h2>Sign in to view rewards</h2><p>Your check-ins and contributor rewards belong to your account.</p><Link className="primary" to="/profile">Sign in</Link></div></section>;
 if(error&&!data)return <section className="page"><Link className="back-link" to="/profile"><ArrowLeft size={16}/>Back to profile</Link><div className="empty-state"><h2>Rewards unavailable</h2><p>{error}</p><button className="secondary" onClick={load}><RefreshCw size={16}/>Retry</button></div></section>;
 if(loading||!data)return <section className="page"><div className="empty-state">Loading rewards…</div></section>;
 return <section className="page">
  <Link className="back-link" to="/profile"><ArrowLeft size={16}/>Back to profile</Link>
  <div className="page-header"><div><span className="eyebrow">COMMUNITY REWARDS</span><h1>Your rewards</h1><p>Every verified check-in contributes to your Kleenest progress.</p></div><div className="hero-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button>{live&&<span className="live-status"><Radio size={14}/>Updated</span>}</div></div>
  <FeatureNavLinks/>
  {error&&<div className="form-error" role="alert">{error}</div>}
  <div className="reward-stats"><div><Trophy/><strong>{data.points??0}</strong><span>points</span></div><div><Star/><strong>{data.level??1}</strong><span>level</span></div><div><strong>{data.total_check_ins??0}</strong><span>check-ins</span></div><div><strong>{data.streak??0}</strong><span>day streak</span></div></div>
  <section className="detail-panel milestone-panel"><div className="panel-heading"><div><span className="eyebrow">CONTRIBUTOR PROGRESS</span><h2>Build trust, not just points</h2></div><ShieldCheck size={24}/></div><p className="observation-copy">Kleenest increases the evidentiary weight of contributors who consistently verify locations. These milestones show exactly how to advance.</p><div className="milestone-list">{milestones.map(m=>{const copy=MILESTONE_COPY[m.milestone_key]||[m.milestone_key,'Contributor milestone'];const done=Boolean(m.achieved);const pct=m.target?Math.min(100,Math.round((m.progress/m.target)*100)):0;return <div className={`milestone-row ${done?'done':''}`} key={m.milestone_key}><div className="milestone-icon">{done?<CheckCircle2 size={19}/>:<ShieldCheck size={19}/>}</div><div className="milestone-main"><div className="milestone-title"><strong>{copy[0]}</strong><span>{done?'Achieved':`${m.progress}/${m.target}`}</span></div><p>{copy[1]}</p><div className="milestone-track"><span style={{width:`${pct}%`}}/></div></div></div>})}</div></section>
  <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">CHALLENGES</span><h2>Turn activity into progress</h2></div><Target size={24}/></div>{challenges.length?<div className="business-intelligence-list">{challenges.map(c=>{const p=challengeProgress.get(c.id)||{};const completed=Boolean(p.completed_at);const target=Number(c.target)||1;const current=Math.min(target,Number(p.progress)||0);const pct=Math.round((current/target)*100);return <div className={`business-row ${completed?'read':''}`} key={c.id}><div><strong>{c.name}</strong><span>{c.description||'Complete this challenge to earn progress.'}</span><small>{current}/{target} · {c.reward_points??0} points{c.reward_badge_code?` · ${c.reward_badge_code}`:''}</small><div className="milestone-track"><span style={{width:`${pct}%`}}/></div></div><button className="secondary" disabled={completed||challengeBusy===c.id} onClick={()=>completeChallenge(c.id)}>{completed?'Completed':challengeBusy===c.id?'Completing…':'Complete'}</button></div>})}</div>:<p>No active challenges are available right now.</p>}</section>
  <section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">BADGES</span><h2>Your earned badges</h2></div><Award size={24}/></div><div className="hero-actions" style={{marginBottom:12}}><button className="secondary" onClick={refreshBadges} disabled={badgeBusy}>{badgeBusy?'Checking…':'Evaluate badges'}</button></div>{badges.length?<div className="milestone-list">{badges.map(b=><div className="milestone-row done" key={b.id}><div className="milestone-icon">{b.icon?<span aria-hidden="true">{b.icon}</span>:<Award size={19}/>}</div><div className="milestone-main"><div className="milestone-title"><strong>{b.name}</strong><span>{b.earned_at?new Date(b.earned_at).toLocaleDateString():''}</span></div><p>{b.description||b.code}</p></div></div>)}</div>:<p>No badges earned yet. Complete challenges and contribute useful evidence to unlock them.</p>}</section>
  <section className="detail-panel reward-history"><div className="panel-heading"><div><span className="eyebrow">LEADERBOARD</span><h2>Community leaders</h2></div><Medal size={24}/></div>{leaderboard.length?leaderboard.slice(0,10).map((row,i)=><div className="reward-row" key={row.user_id||row.id||i}><div><strong>#{i+1} {row.display_name||row.name||'Kleenest member'}</strong><span>{row.level!=null?`Level ${row.level} · `:''}{row.total_check_ins??row.check_ins??0} check-ins</span></div><b>{row.points??row.total_points??0}</b></div>):<p>No leaderboard data yet. Be the first to contribute.</p>}</section>
  <section id="social" className="detail-panel social-panel"><div className="panel-heading"><div><span className="eyebrow">SOCIAL</span><h2>Community activity</h2></div><Users size={24}/></div><p className="observation-copy">Follow contributors you trust and build your own community feed. Reviews, check-ins and verified observations are the social layer of Kleenest.</p>{social.length?social.map(row=>{const isFollowing=following.has(row.user_id);return <article className="social-post" key={row.id}><div className="social-avatar"><Users size={17}/></div><div style={{width:'100%'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><strong>{row.profiles?.display_name||'Kleenest member'}</strong>{row.user_id&&<button className="secondary compact" disabled={followBusy===row.user_id} onClick={()=>toggleFollow(row.user_id)}>{isFollowing?<><UserCheck size={14}/>Following</>:<><UserPlus size={14}/>Follow</>}</button>}</div><span className="social-time">{new Date(row.created_at).toLocaleString()}</span><p><b>{row.places?.name||'A Kleenest location'}</b> · {row.stars}/5</p><p>{row.comment}</p><div className="social-actions"><span><Heart size={14}/> Community signal</span><span><MessageCircle size={14}/> Review</span></div></div></article>}) : <p>No community activity yet. Check in and leave a verified review to start the feed.</p>}<div className="hero-actions"><Link className="secondary" to="/map">Explore the map</Link><Link className="secondary" to="/leaderboard">See everyone</Link></div></section>
  <section className="detail-panel reward-history"><h2>Reward activity</h2>{data.transactions?.length?data.transactions.map(tx=><div className="reward-row" key={tx.id}><div><strong>{String(tx.reason||'reward').replaceAll('_',' ')}</strong><span>{tx.created_at?new Date(tx.created_at).toLocaleString():''}</span></div><b>+{tx.points}</b></div>):<p>No reward activity yet. Check in somewhere to start earning.</p>}</section>
 </section>;
}
