import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Heart, MessageCircle, Trophy, UserRound, Users, RefreshCw } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { getUserLeaderboard } from '../services/rewards';
import { useAuth } from '../context/AuthContext';

export default function SocialPage(){
 const {authenticated,loading:authLoading}=useAuth(); const [reviews,setReviews]=useState([]),[leaders,setLeaders]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{if(!supabase)throw new Error('Supabase is not configured.');const [{data,error:reviewError},leaderboard]=await Promise.all([supabase.from('reviews').select('id,location_id,user_id,stars,comment,created_at,profiles:user_id(display_name,avatar_url),places:location_id(name)').eq('status','published').order('created_at',{ascending:false}).limit(12),authenticated?getUserLeaderboard(10):Promise.resolve([])]);if(reviewError)throw reviewError;setReviews(data||[]);setLeaders(leaderboard||[])}catch(e){setError(e.message||'Community activity is temporarily unavailable.')}finally{setLoading(false)}}
 useEffect(()=>{if(!authLoading)load()},[authLoading,authenticated]); if(authLoading)return <section className="page"><div className="empty-state">Checking your session…</div></section>;
 return <section className="page"><Link className="back-link" to="/profile"><ArrowLeft size={16}/>Back to profile</Link><div className="page-header"><div><span className="eyebrow">KLEENEST COMMUNITY</span><h1>Social</h1><p>See what the community is discovering, verifying, and contributing.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div><div className="social-grid"><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">COMMUNITY FEED</span><h2>Recent activity</h2></div><Users size={24}/></div>{error?<div className="empty-state"><p>{error}</p><button className="secondary" onClick={load}>Retry</button></div>:loading?<div className="empty-state">Loading community activity…</div>:reviews.length?reviews.map(r=><article className="social-post" key={r.id}><div className="social-avatar"><UserRound size={18}/></div><div><strong>{r.profiles?.display_name||'Kleenest member'}</strong><span className="social-time">{new Date(r.created_at).toLocaleString()}</span><p><b>{r.places?.name||'A Kleenest location'}</b> — {r.stars}/5 stars</p><p>{r.comment}</p><div className="social-actions"><span><Heart size={14}/> Community signal</span><span><MessageCircle size={14}/> Review</span></div></div></article>):<p>No community activity yet. Be the first to check in and contribute.</p>}</section><section className="detail-panel"><div className="panel-heading"><div><span className="eyebrow">COMMUNITY RANKINGS</span><h2>Top contributors</h2></div><Trophy size={24}/></div>{leaders.length?leaders.map((r,i)=><div className="reward-row" key={r.user_id||r.id||i}><div><strong>#{i+1} {r.display_name||r.name||'Kleenest member'}</strong><span>Level {r.level??1} · {r.total_check_ins??r.check_ins??0} check-ins</span></div><b>{r.points??r.total_points??0}</b></div>):<p>Sign in and start contributing to appear on the rankings.</p>}<div className="hero-actions"><Link className="primary" to="/rewards">Earn rewards</Link><Link className="secondary" to="/leaderboard">Full leaderboard</Link></div></section></div><section className="detail-panel social-callout"><span className="eyebrow">THE LOOP</span><h2>Discover → Check in → Contribute → Earn → Compete</h2><p>Your activity strengthens location intelligence while your contributions build reputation and rewards.</p><div className="hero-actions"><Link className="secondary" to="/map">Explore the map</Link><Link className="secondary" to="/contests">View contests</Link></div></section></section>;
}
