import { useEffect,useState } from 'react';
import { useLocation } from 'react-router-dom';
import { Accessibility,Camera,Droplets,Gauge,ShieldCheck,Toilet,WashingMachine,MapPinCheck } from 'lucide-react';
import { getPlace } from '../services/places';
import { listLocationFixtures,listLocationHours,listLocationPhotos,getLocationQualitySummary } from '../services/locationIntelligence';
import { recordLocationVisit } from '../services/locationActivity';
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export default function LocationEvidencePanel({locationId:propId}){
 const{pathname}=useLocation();const match=pathname.match(/^\/place\/([^/]+)$/);const routeId=match?decodeURIComponent(match[1]):null;const id=propId||routeId;
 const[s,setS]=useState({loading:false,fixtures:null,hours:[],photos:[],quality:null});const[visitBusy,setVisitBusy]=useState(false);const[visitMessage,setVisitMessage]=useState('');
 useEffect(()=>{let alive=true;if(!id)return;setS(x=>({...x,loading:true}));(async()=>{try{const place=await getPlace(id);const locationId=place?.location_id||place?.id||id;const[fixtures,hours,photos,quality]=await Promise.all([listLocationFixtures(locationId).catch(()=>null),listLocationHours(locationId).catch(()=>[]),listLocationPhotos(locationId).catch(()=>[]),getLocationQualitySummary(locationId).catch(()=>null)]);if(alive)setS({loading:false,fixtures,hours,photos,quality});}catch{if(alive)setS(x=>({...x,loading:false}));}})();return()=>{alive=false}},[id]);
 async function markVisit(){setVisitBusy(true);setVisitMessage('');try{const place=await getPlace(id);const locationId=place?.location_id||place?.id||id;let coords=null;if(typeof navigator!=='undefined'&&navigator.geolocation){coords=await new Promise(resolve=>navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy||null}),()=>resolve(null),{enableHighAccuracy:true,maximumAge:30000,timeout:8000}));}await recordLocationVisit(locationId,{source:'place_visit_button',latitude:coords?.latitude??null,longitude:coords?.longitude??null,accuracy_m:coords?.accuracy_m??null});setVisitMessage('Visit recorded.');}catch(error){setVisitMessage(error?.message||'Unable to record visit.')}finally{setVisitBusy(false)}}
 if(!id||s.loading||(!s.fixtures&&!s.hours.length&&!s.photos.length&&!s.quality))return null;const f=s.fixtures,q=s.quality;return <section className="detail-panel location-evidence-panel" aria-label="Bathroom evidence and what to expect"><div className="panel-heading"><div><span className="eyebrow">BATHROOM INTELLIGENCE</span><h2>What to expect</h2><p>Structured evidence from Kleenest and the community.</p></div><ShieldCheck size={20}/></div><div className="business-action-row"><div><strong>Been here?</strong><span>Record your visit as evidence for this location.</span></div><div><button type="button" className="secondary" onClick={markVisit} disabled={visitBusy}><MapPinCheck size={16}/>{visitBusy?'Recording…':'Record visit'}</button>{visitMessage&&<span className="form-success" role="status">{visitMessage}</span>}</div></div>{f&&<div className="fixture-grid">{[['stalls',f.stalls,Toilet],['urinals',f.urinals,Toilet],['sinks',f.sinks,Droplets],['dryers',f.hand_dryers,WashingMachine],['changing tables',f.changing_tables,Accessibility],['showers',f.showers,Droplets]].filter(([,v])=>v!==null&&v!==undefined).map(([label,value,Icon])=><div className="data-card" key={label}><Icon size={17}/><strong>{value}</strong><span>{label}</span></div>)}</div>}{q&&<div className="quality-grid">{[['Cleanliness',q.cleanliness_score??q.cleanliness],['Accessibility',q.accessibility_score??q.accessibility],['Safety',q.safety_score??q.safety],['Availability',q.availability_score??q.availability],['Condition',q.condition_score??q.condition]].filter(([,v])=>v!==null&&v!==undefined).map(([label,v])=><div key={label}><span>{label}</span><strong>{Number(v).toFixed(1)}/5</strong><Gauge value={Number(v)}/></div>)}</div>}{s.hours.length>0&&<details><summary>Hours</summary><div className="hours-list">{s.hours.map(h=><div key={h.day_of_week}><span>{days[h.day_of_week]||`Day ${h.day_of_week}`}</span><span>{h.is_24_hours?'Open 24 hours':`${h.opens_at?.slice(0,5)||'—'} – ${h.closes_at?.slice(0,5)||'—'}`}</span></div>)}</div></details>}{s.photos.length>0&&<div className="photo-strip"><div className="subheading"><Camera size={16}/> Community photos</div><div>{s.photos.slice(0,6).map(p=><figure key={p.id}><img src={p.public_url||p.url||p.storage_path} alt={p.caption||'Kleenest location'} loading="lazy"/><figcaption>{p.caption||'Location photo'}</figcaption></figure>)}</div></div>}</section>}
