import { useEffect,useRef } from 'react';
import L from 'leaflet';
import { recordDirectionsRequested,recordArrival } from '../services/events';
const DEFAULT_CENTER=[38.627,-90.199];
export default function MapSurface({places=[],onSelect,onBoundsChange}){const nodeRef=useRef(null),mapRef=useRef(null),layerRef=useRef(null);useEffect(()=>{if(!nodeRef.current||mapRef.current)return;const map=L.map(nodeRef.current,{zoomControl:true,attributionControl:true}).setView(DEFAULT_CENTER,11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);layerRef.current=L.layerGroup().addTo(map);mapRef.current=map;const report=()=>{const b=map.getBounds();onBoundsChange?.({south:b.getSouth(),west:b.getWest(),north:b.getNorth(),east:b.getEast()})};map.on('moveend',report);report();return()=>{map.off('moveend',report);map.remove();mapRef.current=null;layerRef.current=null}},[onBoundsChange]);useEffect(()=>{const map=mapRef.current,layer=layerRef.current;if(!map||!layer)return;layer.clearLayers();const valid=places.filter(p=>Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude)));valid.forEach(place=>{const marker=L.marker([Number(place.latitude),Number(place.longitude)]).addTo(layer);const category=String(place.category||'service').replaceAll('_',' ');const locationId=place.location_id||place.id;const score=place.intelligence_score!=null?`<br><strong>Signal ${Math.round(Number(place.intelligence_score))}/100</strong>`:'';const freshness=place.intelligence_freshness_label?`<br><span>${escapeHtml(place.intelligence_freshness_label)}</span>`:'';marker.bindPopup(`<strong>${escapeHtml(place.name)}</strong><br><span>${escapeHtml(category)}</span>${score}${freshness}<br><a href="/place/${encodeURIComponent(place.id)}">Open details</a><br><button data-kleenest-action="directions" data-location-id="${escapeHtml(locationId)}">Get directions</button> <button data-kleenest-action="arrival" data-location-id="${escapeHtml(locationId)}">I arrived</button>`);marker.on('click',()=>onSelect?.(place));marker.on('popupopen',event=>{const root=event.popup.getElement();root?.querySelector('[data-kleenest-action="directions"]')?.addEventListener('click',()=>recordDirections(place));root?.querySelector('[data-kleenest-action="arrival"]')?.addEventListener('click',()=>recordArrival(place));});});if(valid.length===1)map.setView([valid[0].latitude,valid[0].longitude],15);else if(valid.length>1)map.fitBounds(L.latLngBounds(valid.map(p=>[Number(p.latitude),Number(p.longitude)])),{padding:[30,30],maxZoom:14})},[places,onSelect]);return <div ref={nodeRef} className="leaflet-map" aria-label="Kleenest places map"/>}
async function recordDirections(place){const locationId=place.location_id||place.id;try{await recordDirectionsRequested({locationId,placeId:place.id,mode:'driving'});window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${place.latitude},${place.longitude}`)}`,'_blank','noopener,noreferrer')}catch(error){window.alert(error.message||'Unable to open directions.')}}
async function recordArrival(place){const locationId=place.location_id||place.id;try{await recordArrivalEvent(locationId,place.id)}catch(error){window.alert(error.message||'Unable to record arrival.')}}
async function recordArrivalEvent(locationId,placeId){await recordArrival({locationId,placeId,method:'map_popup'})}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
